import {LazyDetails} from './LazyDetails';
import {IndexEvidence} from './IndexEvidence';
import {schemaVerdict} from '../core/schema-verdict';
import {useState} from 'react';
import {Link,useFetcher} from 'react-router';
import type {loadUI} from '../core/ui.server';
import {storeScore} from '../core/store-score';
import {metricPair} from '../core/analytics';
import {visibilityMethod,searchVisibility} from '../core/visibility-score';
import {fieldMeasurement,type SpeedResult} from '../core/performance';
type Data=Awaited<ReturnType<typeof loadUI>>;
function Tile({label,value,children,low=false,warning,action}:{label:string;value:string;children:React.ReactNode;low?:boolean;warning?:string;action?:React.ReactNode}){return <div className={'metric'+(low?' limited-evidence':'')}><div>{label}</div><strong>{value}</strong>{warning&&<p className="health-warning">{warning}</p>}<LazyDetails summary="How this is measured / what to do">{children}</LazyDetails>{action}</div>;}
export function ScoreBoard({d}:{d:Data}){
 const [days,setDays]=useState(28);const check=useFetcher<{ok:boolean;message:string}>();
 const now=Date.parse(d.measuredAt),latest=d.audits[0];const score=storeScore({metrics:d.metrics,technical:latest?.score,schemas:d.discoveries.schemas,healthScores:d.healthScores,observations:d.observations,now});
 const gsc=metricPair(d.metrics,'gsc')[0],ga=metricPair(d.metrics,'ga4')[0],ai=metricPair(d.metrics,'ga4-ai')[0];
 const history=d.metrics.filter(m=>m.provider==='store-score').map(m=>({...JSON.parse(m.payload),day:m.period})).sort((a,b)=>a.day.localeCompare(b.day));
 const comparable=history.filter(m=>m.version===score.version);
 const baseline=comparable.filter(m=>Date.parse(m.day)<=now-days*86400000).at(-1)||comparable[0];
 const availableDays=comparable.length?Math.max(0,Math.floor((now-Date.parse(comparable[0].day))/86400000)):0;
 const elapsed=baseline?Math.max(1,Math.ceil((now-Date.parse(baseline.day))/86400000)):0;
 const delta=comparable.length>1&&baseline?.score!=null&&score.score!==null?score.score-baseline.score:null;
 const trend=history.filter(m=>Date.parse(m.day)>=now-days*86400000&&m.score!==null);
 const money=(snapshot:typeof ga)=>snapshot?.rows?new Intl.NumberFormat('en-GB',{style:'currency',currency:snapshot.currency||'GBP'}).format(snapshot.rows.reduce((n:number,r:{metricValues?:{value:string}[]})=>n+Number(r.metricValues?.[1]?.value||0),0)):'Not measured';
 const n=(v:number|null|undefined)=>v==null?'Not measured':`${Math.round(v)}/100`;
 const speed=metricPair(d.metrics,'pagespeed')[0] as SpeedResult|undefined;
 const indexJob=d.jobs.find(j=>j.kind==='indexation'&&['queued','running'].includes(j.status));
 const progress=indexJob?JSON.parse(indexJob.payload).progress:null;
 const engineSamples=d.observations.filter(o=>now-new Date(o.createdAt).getTime()<=28*86400000);const engines=[...new Set(engineSamples.map(o=>o.engine==='openai'?'ChatGPT':o.engine))];
 const idx=metricPair(d.metrics,'indexation')[0];
 const schemas=(d.discoveries.schemas||[]) as {url:string;types:unknown[];valid?:boolean}[];const present=schemas.filter(s=>s.types.length);const valid=present.filter(s=>schemaVerdict(s).pass).length;
 const schemaReasons=new Map<string,number>();for(const row of schemas){for(const reason of schemaVerdict(row).errors)schemaReasons.set(reason,(schemaReasons.get(reason)||0)+1);}
 return <>
 <section className="card store-score-hero" aria-label="Store Score"><div className="card-head"><h2>Store Score</h2><label>Trend period<select disabled={availableDays<7} value={days} onChange={e=>setDays(Number(e.target.value))}><option value="7">7 days</option><option value="28" disabled={availableDays<28}>28 days</option><option value="90" disabled={availableDays<90}>90 days</option></select></label></div>{availableDays<7&&<p>Building history: fewer than seven days recorded. Longer trend periods become available as measurements accumulate.</p>}<strong className="store-score-number">{n(score.score)}</strong><p>{delta===null?'Record a second measurement to see movement. Existing measurements are retained across releases.':`${delta>=0?'+':''}${delta} points${baseline.score>0?` (${delta>=0?'+':''}${(100*delta/baseline.score).toFixed(1)}%)`:''} over ${Math.min(days,elapsed)} ${Math.min(days,elapsed)===1?'day':'days'} of data so far.`}</p>{score.limited&&<p className="badge">Limited evidence{score.capped?' · capped at 55':''} · {score.coverage}% of weighted components measured</p>}
 {trend.length>1&&<svg viewBox="0 0 600 100" role="img" aria-label="Recorded Store Score trend" className="score-sparkline"><polyline fill="none" stroke="currentColor" strokeWidth="3" points={trend.map((m,i)=>`${5+590*i/(trend.length-1)},${95-.9*m.score}`).join(' ')}/></svg>}
 <p>Missing measurements are rescaled: 100/100 remains the mathematical maximum. {score.capped?'A separate evidence rule currently caps this score at 55 because fewer than 10 recent Google clicks have been recorded.':''}</p><details><summary>What changed and how the score works</summary><p>Method 3 gives structured data 30% of technical health. Older measurements remain in history with their method number; changes between methods are not treated as improvements.</p><p>A RankPilot indicator, not a Google rating. Missing components are excluded and remaining weights are rescaled; this makes it a partial score. Fewer than 10 clicks or missing recent search evidence caps the headline at 55. Grey components have limited evidence. Readiness and content coverage overlap other components by design.</p><div className="table-wrap"><table><thead><tr><th>Component</th><th>Weight</th><th>Now</th><th>Movement</th><th>Evidence</th></tr></thead><tbody>{score.parts.map(p=>{const before=baseline?.parts?.find((b:{key:string})=>b.key===p.key)?.value;return <tr key={p.key} className={p.low?'limited-evidence':''}><td>{p.label}</td><td>{p.weight}%</td><td>{n(p.value)}</td><td>{before!=null&&p.value!==null?`${(p.value-before).toFixed(1)} points`:'No comparable baseline'}</td><td>{p.low?'Low confidence. ':''}{p.note}</td></tr>;})}</tbody></table></div><p>Fixes saved in the same period are listed below. Their timing does not prove they caused a score, traffic or revenue movement. A score can change when new evidence arrives, even with no content edits.</p>{d.changes.filter(c=>['applied','rolled_back'].includes(c.status)&&c.appliedAt&&now-new Date(c.appliedAt).getTime()<=days*86400000).slice(0,10).map(c=><p key={c.id}>{new Date(c.appliedAt!).toLocaleDateString('en-GB')} · {d.resources.find(r=>r.id===c.resourceId)?.title||'Store update'} · {c.feature} · {c.status==='rolled_back'?'Undone':'Applied'}</p>)}<Link to="/app/reports">Open complete change history and impact tracking →</Link></details></section>
 <div className="metrics-grid search-score-grid">
 <Tile label="Google search visibility" value={n(score.search?.score)} low={score.parts[0].low}><p>{score.search?`${score.search.clicks} clicks / ${score.search.impressions} impressions · ${score.search.start} to ${score.search.end}.`:'Connect Search Console and refresh analytics.'}</p><p>{visibilityMethod}</p><Link to="/app/reports">Explore the searches that reach your shop →</Link></Tile>
 <Tile label="Technical health" value={n(score.technical.score)} low={score.technical.partial}><p>{score.parts[1].note} This measures setup, not search position.</p>{score.technical.parts.map(p=><p key={p.label}>{p.label}: {n(p.value)} · {p.weight}% base weight</p>)}<Link to="/app/audit">Inspect checks and scan coverage →</Link></Tile></div>
 <div className="metrics-grid dashboard-metrics">
 <Tile label="Discovery readiness" value={n(score.readiness)} low={score.parts[2].low}><p>{score.parts[2].note} Missing search data leaves this unmeasured.</p><p>{visibilityMethod}</p><Link to="/app/audit">Find the next improvement →</Link></Tile>
 <Tile label="AI visibility" value={score.ai===null?'Not measured':`${Math.round(score.ai)}%`} warning={score.ai===null?undefined:`${engines.join(', ')} · ${score.samples} recent answer samples`} low={score.parts[3].low}><p>{score.parts[3].note} API observations do not represent all consumer answers.</p><Link to="/app/aeo">Explore AI visibility and FAQs →</Link></Tile>
 <Tile label="Organic revenue" value={money(ga)}><p>{ga?.start?`${ga.start} to ${ga.end} · Google Analytics Organic Search attribution.`:'Connect Google Analytics and refresh analytics.'} This is attributed revenue, not proof a RankPilot edit caused a sale.</p><Link to="/app/reports">See revenue evidence →</Link></Tile>
 <Tile label="AI referral revenue" value={money(ai)}><p>{ai?.start?`${ai.start} to ${ai.end}.`:''} Google Analytics sessions with identifiable AI referrers. Unidentified referrers are not measurable; this is not a Shopify order-level reconciliation.</p><Link to="/app/reports">See recorded referrals →</Link></Tile></div>
 <div className="catalogue-tiles">{[['product','Products','products'],['collection','Collections','collections'],['article','Blogs','content']].map(([kind,label,path])=>{const performance=searchVisibility(gsc,kind,now);return <div className="card catalogue-tile" key={kind}><Link to={`/app/${path}`}><h2>{label==='Products'?'Product':label==='Collections'?'Collection':'Blog'} setup ↗</h2><strong>{n(d.healthScores?.[kind]?.score)}</strong></Link>{performance && <p className={performance.clicks<10?"health-warning":"muted"}>Observed search visibility: {n(performance.score)} · {performance.clicks} reported clicks</p>}<p>{performance?`${performance.pages} pages received ${performance.impressions} Google impressions and ${performance.clicks} clicks · ${performance.start} to ${performance.end}.`:"Refresh Search Console to see how many pages reach shoppers."}</p><details><summary>How this is measured / what to do</summary><p>Health = 100 × (1 − failed checks ÷ applicable checks). {d.healthScores?.[kind]?.failed??0} failed / {d.healthScores?.[kind]?.checks??0} applicable checks. Scores measure the audited setup, not traffic.</p><p>Technical health across {d.resources.filter(r=>r.kind===kind).length} pages. Open {label.toLowerCase()} to review source-based suggestions. Search visibility: {n(performance?.score)}; {performance?.clicks??'unmeasured'} reported clicks. Setup and traffic are different measures.</p></details></div>;})}</div>
 <p className="muted">Coverage: {idx?.submitted??'unmeasured'} sitemap URLs · {schemas.length} pages scanned for structured data · Search Console counts below cover only pages with reported impressions. These are different measured populations, not interchangeable site totals.</p><div className="metrics-grid additional-metrics">
 <Tile label="Store speed / Core Web Vitals" value={n(speed?.score==null?null:speed.score*100)}><p>{speed?.url||'Run a mobile speed check.'} {speed?.checkedAt?`Checked ${new Date(speed.checkedAt).toLocaleString('en-GB')}.`:''} Score is a Lighthouse lab measurement, not a Core Web Vitals pass.</p>{['LARGEST_CONTENTFUL_PAINT_MS','CUMULATIVE_LAYOUT_SHIFT_SCORE','INTERACTION_TO_NEXT_PAINT'].map(k=><p key={k}>{fieldMeasurement(k,speed?.field?.metrics?.[k]?.percentile)}</p>)}<Link to="/app/reports#page-speed">Run a check and review speed improvements →</Link></Tile>
 <Tile label="Indexation coverage" value={idx?.inspected?`${idx.indexed} of ${idx.inspected} checked URLs indexed`:'Not measured'} action={<><check.Form method="post" action="/app?index" preventScrollReset><input type="hidden" name="intent" value="indexation"/><button className="button" disabled={check.state!=='idle'||!!indexJob}>{indexJob?'Checking sitemap URLs…':check.state==='idle'?'Check next 20 URLs':'Queuing…'}</button></check.Form>{indexJob&&progress&&<p role="status">{progress.checked} of {progress.total} sitemap URLs checked. You can continue using the app.</p>}{check.data&&<p role="status">{check.data.message}</p>}</>} warning={idx?'Inspection coverage: '+idx.inspected+' of '+idx.submitted+' sitemap URLs ('+Math.round(100*idx.inspected/Math.max(1,idx.submitted))+'%)':'Use Check next 20 URLs below; also starts after a connected analytics refresh.'}><p>{idx?`${idx.indexed} confirmed indexed among ${idx.inspected} inspected in the last 28 days. The sitemap contains ${idx.submitted} URLs; ${Math.max(0,idx.submitted-idx.inspected)} remain unknown.${idx.limited?' Sitemap discovery was limited; this is not the whole site.':''}`:'Check sitemap URLs against Google’s stored index, 20 per run. Unknown URLs are never counted as unindexed.'}</p>{idx&&<LazyDetails summary="URL evidence and checks that need attention"><p>{idx.note}</p>{idx.errors?.map((e:string)=><p key={e}>{e}</p>)}<IndexEvidence lastRecheck={idx.lastRecheck}/></LazyDetails>}</Tile>
 <Tile label="Structured-data health" value={n(score.technical.schema)} warning={score.technical.schema!==null&&score.technical.schema<50?`${schemas.length-valid} scanned pages need attention · ${schemas.length-present.length} have no markup; ${present.length-valid} have incomplete or invalid markup`:undefined}><p>{valid} pages pass RankPilot’s schema checks out of {schemas.length} scanned pages. {schemas.length-present.length} scanned pages have none. This is a local validation result, not guaranteed Google rich-result eligibility.</p><ul>{[...schemaReasons].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([reason,count])=><li key={reason}>{count} pages: {reason}</li>)}</ul><p>Pass rates can change when the scanned pages or validation checks change. Compare dated scan evidence before attributing a drop to the site; older snapshots do not retain enough page-level evidence to explain every historical change.</p><Link to="/app/aeo">Inspect schema coverage and missing details →</Link></Tile>
 </div>
 </>;
}
export function StoreProgress({d}:{d:Data}){
 const [historyPage,setHistoryPage]=useState(0);
 const rows=d.metrics.filter(m=>m.provider==='store-score').sort((a,b)=>a.period.localeCompare(b.period)).map(m=>({...JSON.parse(m.payload),day:m.period}));
 return <section className="card"><h2>Progress after your changes</h2><p>{d.appliedCount} verified changes saved. Measurements are retained across releases. Method changes are labelled below; they are not evidence of a traffic improvement.</p>{rows.length>1?<><svg viewBox="0 0 800 140" role="img" aria-label="Recorded Store Score and saved change counts" style={{width:'100%',height:170}}><line x1="15" x2="785" y1="125" y2="125" stroke="#dce3df"/><polyline fill="none" stroke="#27644e" strokeWidth="3" points={rows.filter(r=>r.score!==null).map((r,i)=>`${15+i*770/Math.max(1,rows.length-1)},${125-r.score}`).join(' ')}/></svg><details><summary>Recorded scores and fixes</summary><table><thead><tr><th>Date</th><th>Store Score / method</th><th>Saved changes</th></tr></thead><tbody>{rows.slice(historyPage*20,(historyPage+1)*20).map(r=><tr key={r.day}><td>{r.day}</td><td>{r.score===null?'Not measured':`${r.score}/100 · method ${r.version}`}</td><td>{r.appliedCount}</td></tr>)}</tbody></table><button className="button" disabled={!historyPage} onClick={()=>setHistoryPage(historyPage-1)}>Previous measurements</button> <button className="button" disabled={(historyPage+1)*20>=rows.length} onClick={()=>setHistoryPage(historyPage+1)}>Next measurements</button></details></>:<p>Run a scan or refresh analytics to record a measurement. More dates will build the trend.</p>}<p>Score movement and fixes are shown together for context; this does not prove that a fix caused the movement. Open a saved fix in Results &amp; history for its own before/after search baseline.</p><Link to="/app/reports">Track saved fixes and results →</Link></section>;
}
