import {useState} from 'react';
export function TrafficTrend({daily,observations}:{daily?:{start:string;end:string;rows:{keys:string[];clicks:number}[]};observations:{createdAt:Date|string;cited:boolean}[]}){
 const [page,setPage]=useState(0);
 if(!daily)return <section className="card"><h2>Last 90 days</h2><p>Refresh connected analytics in Results &amp; history to load the search trend. AI history builds from recorded samples; it is never backfilled with invented results.</p></section>;
 const rows=[...daily.rows].sort((a,b)=>a.keys[0].localeCompare(b.keys[0]));
 const max=Math.max(1,...rows.map(r=>r.clicks));const start=new Date(daily.start).getTime();const duration=Math.max(86400000,new Date(daily.end).getTime()-start);
 const points=rows.map(r=>`${20+760*(new Date(r.keys[0]).getTime()-start)/duration},${130-110*r.clicks/max}`).join(' ');
 const days=new Map<string,{count:number;cited:number}>();for(const o of observations){const key=new Date(o.createdAt).toISOString().slice(0,10);if(key<daily.start||key>daily.end)continue;const v=days.get(key)||{count:0,cited:0};v.count++;v.cited+=Number(o.cited);days.set(key,v);}
 return <section className="card"><h2>Last 90 days</h2><p>Google search clicks · {daily.start} to {daily.end}. Higher traffic after an edit does not establish that the edit caused it.</p>{rows.length>1?<svg viewBox="0 0 800 150" role="img" aria-label={`Daily Google clicks, scale zero to ${max}`} style={{width:'100%',height:180}}><text x="0" y="16">{max}</text><text x="0" y="133">0</text><line x1="20" x2="790" y1="130" y2="130" stroke="#dce3df"/><polyline points={points} stroke="#3182ce" strokeWidth="3" fill="none"/></svg>:<p>Not enough daily results for a line chart.</p>}<details><summary>AI citation observations and daily values</summary><p>AI samples have a different denominator and sampling schedule, so they are shown separately from clicks.</p>{[...days].sort().slice(page*20,(page+1)*20).map(([day,v])=><p key={day}>{day}: cited in {v.cited}/{v.count} answers</p>)}{!days.size&&<p>No AI observations in this reporting period.</p>}{rows.slice(page*20,(page+1)*20).map(r=><p key={r.keys[0]}>{r.keys[0]}: {r.clicks} Google clicks</p>)}<button className="button" disabled={!page} onClick={()=>setPage(page-1)}>Previous daily evidence</button> <button className="button" disabled={(page+1)*20>=Math.max(rows.length,days.size)} onClick={()=>setPage(page+1)}>Next daily evidence</button></details></section>;
}
