export const sectionGuide:Record<string,{shows:string;steps:string[]}>={
 dashboard:{shows:'A summary of the latest audit, proposals awaiting review and changes applied to Shopify. Scores describe the audit checks, not your Google ranking.',steps:['Run an audit to check your store.','Open Find issues to choose a problem, or Review & apply to check an existing proposal.','An accepted change is still waiting to be applied. Applied means its saved value was checked in Shopify.']},
 audit:{shows:'Issues found in your catalogue and sampled storefront pages. A page can have several findings. Some notices need information or a theme-specific edit.',steps:['Filter by issue or search for a page.','Choose Generate fix to create a preview, or follow the guidance for a manual finding.','Review the before and after values. Accept to apply the change, or reject to keep the current content.']},
 reviews:{shows:'Proposed changes and their progress: pending, accepted, applying, applied, rejected or failed.',steps:['Open a proposal to compare Before and After.','Accept and apply sends that exact change to Shopify. Reject leaves Shopify unchanged.','For a failed change, open its error and use Retry and verify when available. Check Applied before treating it as complete.']},
 products:{shows:'Products imported from Shopify, their keywords and audit findings. Product titles and search snippets are separate fields.',steps:['Select one or more products and choose what to improve.','Generate previews, then open Review & apply. Nothing publishes during generation.','Use Facts & keyword to fill missing information. Auto-populate extracts existing specifications; check each suggestion before confirming it.']},
 collections:{shows:'Collection pages, their search keywords and copy, plus redirects for retired collection paths.',steps:['Select a collection and generate a preview for the field you want to improve.','Accept the preview in Review & apply.','For a retired URL, propose a redirect to a relevant live collection and review the destination before acceptance.']},
 content:{shows:'Ideas and unpublished blog drafts based on catalogue information.',steps:['Choose a topic and relevant products.','Generate a draft and check its facts, wording and links.','Draft creation does not publish a blog post. Review the draft in Shopify before publishing.']},
 aeo:{shows:'Product FAQs, structured-data guidance and optional measurements of mentions in AI answers.',steps:['Confirm sourced product facts before generating FAQs.','Review and accept FAQ proposals, then check their storefront display.','Configure a provider before measuring AI mentions. A mention sample is not a search ranking.']},
 reports:{shows:'Connected performance data, reports and the history of store changes. Blank metrics mean no data is connected or available.',steps:['Connect measurement services in Settings if you want traffic data.','Compare dates and view the change history.','Use a change preview to inspect its saved values or roll back an applied change.']},
 settings:{shows:'Store preferences, external service connections and credentials.',steps:['Configure only the providers you want to use.','Save preferences separately from encrypted credentials.','Autopilot remains off: generated proposals require acceptance before application.']}
};
