FROM node:22-bookworm-slim
RUN apt-get update && apt-get install -y openssl ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY rankpilot-source.tar.gz /tmp/rankpilot-source.tar.gz
RUN tar -xzf /tmp/rankpilot-source.tar.gz --strip-components=1 -C /app && rm /tmp/rankpilot-source.tar.gz
COPY patches/generation.server.ts /app/app/core/generation.server.ts
COPY patches/generation.test.ts /app/tests/generation.test.ts
COPY patches/Workspace.tsx /app/app/components/Workspace.tsx
COPY patches/job-feedback.ts /app/app/core/job-feedback.ts
COPY patches/ui.server.ts /app/app/core/ui.server.ts
COPY patches/job-feedback.test.ts /app/tests/job-feedback.test.ts
COPY patches/service.server.ts /app/app/core/service.server.ts
COPY patches/catalogue.ts /app/app/core/catalogue.ts
COPY patches/finding-workflow.ts /app/app/core/finding-workflow.ts
COPY patches/health.ts /app/app/routes/health.ts
COPY patches/worker.ts /app/scripts/worker.ts
COPY patches/generate-feedback.test.ts /app/tests/generate-feedback.test.ts
COPY patches/finding-workflow.test.ts /app/tests/finding-workflow.test.ts
COPY patches/workflow-lifecycle.test.ts /app/tests/workflow-lifecycle.test.ts
COPY patches/app.tsx /app/app/routes/app.tsx
COPY patches/section-guide.ts /app/app/core/section-guide.ts
COPY patches/job-revision.ts /app/app/core/job-revision.ts
COPY patches/app.job-status.ts /app/app/routes/app.job-status.ts
COPY patches/proposal-repair.server.ts /app/app/core/proposal-repair.server.ts
COPY patches/proposal-repair.test.ts /app/tests/proposal-repair.test.ts
COPY patches/release5/app/components/ChangeValues.tsx /app/app/components/ChangeValues.tsx
COPY patches/release5/app/components/Connections.tsx /app/app/components/Connections.tsx
COPY patches/release5/app/components/Download.tsx /app/app/components/Download.tsx
COPY patches/release5/app/components/SectionHeading.tsx /app/app/components/SectionHeading.tsx
COPY patches/release5/app/core/analytics.ts /app/app/core/analytics.ts
COPY patches/release5/app/core/connections.ts /app/app/core/connections.ts
COPY patches/release5/app/core/context.server.ts /app/app/core/context.server.ts
COPY patches/release5/app/core/crawl.server.ts /app/app/core/crawl.server.ts
COPY patches/release5/app/core/integrations.server.ts /app/app/core/integrations.server.ts
COPY patches/release5/app/core/jobs.server.ts /app/app/core/jobs.server.ts
COPY patches/release5/app/core/proposal-value.ts /app/app/core/proposal-value.ts
COPY patches/release5/app/core/shopify-api.server.ts /app/app/core/shopify-api.server.ts
COPY patches/release5/app/core/subsection-guide.ts /app/app/core/subsection-guide.ts
COPY patches/release5/app/core/ui-data.server.ts /app/app/core/ui-data.server.ts
COPY patches/release5/app/core/worker-health.server.ts /app/app/core/worker-health.server.ts
COPY patches/release5/app/routes/app._index.tsx /app/app/routes/app._index.tsx
COPY patches/release5/app/routes/app.resource.ts /app/app/routes/app.resource.ts
COPY patches/release5/app/routes/webhooks.privacy.tsx /app/app/routes/webhooks.privacy.tsx
COPY patches/release5/app/styles.css /app/app/styles.css
COPY patches/release5/tests/audit-reproductions.test.ts /app/tests/audit-reproductions.test.ts
COPY patches/release5/tests/content-safeguards.test.ts /app/tests/content-safeguards.test.ts
COPY patches/release5/tests/core.test.ts /app/tests/core.test.ts
COPY patches/release5/tests/release5-ui.test.ts /app/tests/release5-ui.test.ts
COPY patches/release5/prisma/migrations/20260924220000_generation_cache/migration.sql /app/prisma/migrations/20260924220000_generation_cache/migration.sql
COPY patches/release5/prisma/schema.prisma /app/prisma/schema.prisma
COPY patches/release51/ReviewActions.tsx /app/app/components/ReviewActions.tsx
COPY patches/release51/review-actions.test.ts /app/tests/review-actions.test.ts
COPY patches/release6/app/routes/health.ts /app/app/routes/health.ts
COPY patches/release6/app/components/FactImport.tsx /app/app/components/FactImport.tsx
COPY patches/release6/app/components/Workspace.tsx /app/app/components/Workspace.tsx
COPY patches/release6/app/core/workflow-ui.ts /app/app/core/workflow-ui.ts
COPY patches/release6/app/core/catalogue.ts /app/app/core/catalogue.ts
COPY patches/release6/app/core/types.ts /app/app/core/types.ts
COPY patches/release6/app/core/fact-import.ts /app/app/core/fact-import.ts
COPY patches/release6/app/core/ui.server.ts /app/app/core/ui.server.ts
COPY patches/release6/app/core/content-policy.ts /app/app/core/content-policy.ts
COPY patches/release6/app/core/job-revision.ts /app/app/core/job-revision.ts
COPY patches/release6/app/core/job-feedback.ts /app/app/core/job-feedback.ts
COPY patches/release6/app/core/subsection-guide.ts /app/app/core/subsection-guide.ts
COPY patches/release6/app/core/generation.server.ts /app/app/core/generation.server.ts
COPY patches/release6/app/core/service.server.ts /app/app/core/service.server.ts
COPY patches/release6/tests/core.test.ts /app/tests/core.test.ts
COPY patches/release6/tests/job-feedback.test.ts /app/tests/job-feedback.test.ts
COPY patches/release6/tests/workflow-lifecycle.test.ts /app/tests/workflow-lifecycle.test.ts
COPY patches/release6/tests/feedback-ui.mjs /app/tests/feedback-ui.mjs
COPY patches/release6/tests/feedback-regressions.test.ts /app/tests/feedback-regressions.test.ts
COPY patches/release7/app/components/BatchReview.tsx /app/app/components/BatchReview.tsx
COPY patches/release7/app/components/ChangeValues.tsx /app/app/components/ChangeValues.tsx
COPY patches/release7/app/components/FactImport.tsx /app/app/components/FactImport.tsx
COPY patches/release7/app/components/SectionHeading.tsx /app/app/components/SectionHeading.tsx
COPY patches/release7/app/components/Workspace.tsx /app/app/components/Workspace.tsx
COPY patches/release7/app/core/finding-workflow.ts /app/app/core/finding-workflow.ts
COPY patches/release7/app/core/job-feedback.ts /app/app/core/job-feedback.ts
COPY patches/release7/app/core/live-workspace.ts /app/app/core/live-workspace.ts
COPY patches/release7/app/core/merchant-copy.ts /app/app/core/merchant-copy.ts
COPY patches/release7/app/core/section-guide.ts /app/app/core/section-guide.ts
COPY patches/release7/app/core/service.server.ts /app/app/core/service.server.ts
COPY patches/release7/app/core/shopify-api.server.ts /app/app/core/shopify-api.server.ts
COPY patches/release7/app/core/subsection-guide.ts /app/app/core/subsection-guide.ts
COPY patches/release7/app/core/ui.server.ts /app/app/core/ui.server.ts
COPY patches/release7/app/core/workflow-ui.ts /app/app/core/workflow-ui.ts
COPY patches/release7/app/routes/app.live-state.ts /app/app/routes/app.live-state.ts
COPY patches/release7/app/routes/app.tsx /app/app/routes/app.tsx
COPY patches/release7/app/routes/health.ts /app/app/routes/health.ts
COPY patches/release7/tests/feedback-regressions.test.ts /app/tests/feedback-regressions.test.ts
COPY patches/release7/tests/feedback-ui.mjs /app/tests/feedback-ui.mjs
COPY patches/release7/tests/release5-ui.test.ts /app/tests/release5-ui.test.ts
COPY patches/release7/tests/retest7.test.ts /app/tests/retest7.test.ts
COPY patches/release7/tests/workflow-lifecycle.test.ts /app/tests/workflow-lifecycle.test.ts
COPY patches/release8/app/styles.css /app/app/styles.css
COPY patches/release8/app/routes/health.ts /app/app/routes/health.ts
COPY patches/release8/app/routes/app.tsx /app/app/routes/app.tsx
COPY patches/release8/app/components/Dashboard.tsx /app/app/components/Dashboard.tsx
COPY patches/release8/app/components/TechnicalTools.tsx /app/app/components/TechnicalTools.tsx
COPY patches/release8/app/components/PageSpeedResults.tsx /app/app/components/PageSpeedResults.tsx
COPY patches/release8/app/components/TrafficTrend.tsx /app/app/components/TrafficTrend.tsx
COPY patches/release8/app/components/Workspace.tsx /app/app/components/Workspace.tsx
COPY patches/release8/app/core/crawl.server.ts /app/app/core/crawl.server.ts
COPY patches/release8/app/core/integrations.server.ts /app/app/core/integrations.server.ts
COPY patches/release8/app/core/dashboard.ts /app/app/core/dashboard.ts
COPY patches/release8/app/core/technical-audit.ts /app/app/core/technical-audit.ts
COPY patches/release8/app/core/types.ts /app/app/core/types.ts
COPY patches/release8/app/core/merchant-copy.ts /app/app/core/merchant-copy.ts
COPY patches/release8/app/core/ui.server.ts /app/app/core/ui.server.ts
COPY patches/release8/app/core/subsection-guide.ts /app/app/core/subsection-guide.ts
COPY patches/release8/app/core/generation.server.ts /app/app/core/generation.server.ts
COPY patches/release8/app/core/service.server.ts /app/app/core/service.server.ts
COPY patches/release8/app/core/performance.ts /app/app/core/performance.ts
COPY patches/release8/tests/release8.test.ts /app/tests/release8.test.ts
COPY patches/release8/tests/feedback-ui.mjs /app/tests/feedback-ui.mjs
COPY patches/release9/app/components/ChangeReview.tsx /app/app/components/ChangeReview.tsx
COPY patches/release9/app/components/Dashboard.tsx /app/app/components/Dashboard.tsx
COPY patches/release9/app/components/FixArena.tsx /app/app/components/FixArena.tsx
COPY patches/release9/app/components/Workspace.tsx /app/app/components/Workspace.tsx
COPY patches/release9/app/core/analytics.ts /app/app/core/analytics.ts
COPY patches/release9/app/core/finding-workflow.ts /app/app/core/finding-workflow.ts
COPY patches/release9/app/core/merchant-copy.ts /app/app/core/merchant-copy.ts
COPY patches/release9/app/core/subsection-guide.ts /app/app/core/subsection-guide.ts
COPY patches/release9/app/routes/health.ts /app/app/routes/health.ts
COPY patches/release9/app/styles.css /app/app/styles.css
COPY patches/release9/tests/feedback-ui.mjs /app/tests/feedback-ui.mjs
COPY patches/release9/tests/usability9.test.ts /app/tests/usability9.test.ts
COPY patches/release10/app/components/FixArena.tsx /app/app/components/FixArena.tsx
COPY patches/release10/app/components/Dashboard.tsx /app/app/components/Dashboard.tsx
COPY patches/release10/app/components/TechnicalTools.tsx /app/app/components/TechnicalTools.tsx
COPY patches/release10/app/routes/health.ts /app/app/routes/health.ts
COPY patches/release10/app/core/broken-url.ts /app/app/core/broken-url.ts
COPY patches/release10/app/core/service.server.ts /app/app/core/service.server.ts
COPY patches/release10/app/core/ui.server.ts /app/app/core/ui.server.ts
COPY patches/release10/app/core/remove-link.ts /app/app/core/remove-link.ts
COPY patches/release10/app/core/catalogue.ts /app/app/core/catalogue.ts
COPY patches/release10/tests/feedback-ui.mjs /app/tests/feedback-ui.mjs
COPY patches/release10/tests/fixes10.test.ts /app/tests/fixes10.test.ts
COPY patches/release11/app/components/BatchReview.tsx /app/app/components/BatchReview.tsx
COPY patches/release11/app/components/ChangeReview.tsx /app/app/components/ChangeReview.tsx
COPY patches/release11/app/components/Dashboard.tsx /app/app/components/Dashboard.tsx
COPY patches/release11/app/components/FixArena.tsx /app/app/components/FixArena.tsx
COPY patches/release11/app/components/TechnicalTools.tsx /app/app/components/TechnicalTools.tsx
COPY patches/release11/app/components/Workspace.tsx /app/app/components/Workspace.tsx
COPY patches/release11/app/core/broken-url.ts /app/app/core/broken-url.ts
COPY patches/release11/app/core/catalogue.ts /app/app/core/catalogue.ts
COPY patches/release11/app/core/content-policy.ts /app/app/core/content-policy.ts
COPY patches/release11/app/core/crawl.server.ts /app/app/core/crawl.server.ts
COPY patches/release11/app/core/dashboard.ts /app/app/core/dashboard.ts
COPY patches/release11/app/core/generation.server.ts /app/app/core/generation.server.ts
COPY patches/release11/app/core/job-feedback.ts /app/app/core/job-feedback.ts
COPY patches/release11/app/core/link-diagnosis.ts /app/app/core/link-diagnosis.ts
COPY patches/release11/app/core/merchant-copy.ts /app/app/core/merchant-copy.ts
COPY patches/release11/app/core/proposal-repair.server.ts /app/app/core/proposal-repair.server.ts
COPY patches/release11/app/core/proposal-value.ts /app/app/core/proposal-value.ts
COPY patches/release11/app/core/remove-link.ts /app/app/core/remove-link.ts
COPY patches/release11/app/core/search-copy.ts /app/app/core/search-copy.ts
COPY patches/release11/app/core/service.server.ts /app/app/core/service.server.ts
COPY patches/release11/app/core/shopify-api.server.ts /app/app/core/shopify-api.server.ts
COPY patches/release11/app/core/subsection-guide.ts /app/app/core/subsection-guide.ts
COPY patches/release11/app/core/technical-audit.ts /app/app/core/technical-audit.ts
COPY patches/release11/app/core/types.ts /app/app/core/types.ts
COPY patches/release11/app/core/ui-data.server.ts /app/app/core/ui-data.server.ts
COPY patches/release11/app/core/ui.server.ts /app/app/core/ui.server.ts
COPY patches/release11/app/core/visibility-score.ts /app/app/core/visibility-score.ts
COPY patches/release11/app/routes/health.ts /app/app/routes/health.ts
COPY patches/release11/app/styles.css /app/app/styles.css
COPY patches/release11/tests/backlog11.test.ts /app/tests/backlog11.test.ts
COPY patches/release11/tests/feedback-regressions.test.ts /app/tests/feedback-regressions.test.ts
COPY patches/release11/tests/feedback-ui.mjs /app/tests/feedback-ui.mjs
COPY patches/release11/tests/generation.test.ts /app/tests/generation.test.ts
COPY patches/release11/tests/link-verification11.test.ts /app/tests/link-verification11.test.ts
COPY patches/release11/tests/proposal-repair.test.ts /app/tests/proposal-repair.test.ts
COPY patches/release11/tests/review-actions.test.ts /app/tests/review-actions.test.ts
COPY patches/release11/tests/workflow-lifecycle.test.ts /app/tests/workflow-lifecycle.test.ts
COPY patches/release11/scripts/worker.ts /app/scripts/worker.ts
COPY patches/release12/app/components/ChangeImpact.tsx /app/app/components/ChangeImpact.tsx
COPY patches/release12/app/components/ChangeReview.tsx /app/app/components/ChangeReview.tsx
COPY patches/release12/app/components/Dashboard.tsx /app/app/components/Dashboard.tsx
COPY patches/release12/app/components/FixArena.tsx /app/app/components/FixArena.tsx
COPY patches/release12/app/components/ScoreBoard.tsx /app/app/components/ScoreBoard.tsx
COPY patches/release12/app/components/SourceSuggestions.tsx /app/app/components/SourceSuggestions.tsx
COPY patches/release12/app/components/Workspace.tsx /app/app/components/Workspace.tsx
COPY patches/release12/app/core/generation.server.ts /app/app/core/generation.server.ts
COPY patches/release12/app/core/indexation.server.ts /app/app/core/indexation.server.ts
COPY patches/release12/app/core/integrations.server.ts /app/app/core/integrations.server.ts
COPY patches/release12/app/core/link-intelligence.ts /app/app/core/link-intelligence.ts
COPY patches/release12/app/core/live-workspace.ts /app/app/core/live-workspace.ts
COPY patches/release12/app/core/measurement.server.ts /app/app/core/measurement.server.ts
COPY patches/release12/app/core/service.server.ts /app/app/core/service.server.ts
COPY patches/release12/app/core/shopify-api.server.ts /app/app/core/shopify-api.server.ts
COPY patches/release12/app/core/source-drafts.ts /app/app/core/source-drafts.ts
COPY patches/release12/app/core/store-score.ts /app/app/core/store-score.ts
COPY patches/release12/app/core/suggestions.server.ts /app/app/core/suggestions.server.ts
COPY patches/release12/app/core/types.ts /app/app/core/types.ts
COPY patches/release12/app/core/ui-data.server.ts /app/app/core/ui-data.server.ts
COPY patches/release12/app/core/ui.server.ts /app/app/core/ui.server.ts
COPY patches/release12/app/routes/app.resource.ts /app/app/routes/app.resource.ts
COPY patches/release12/app/routes/health.ts /app/app/routes/health.ts
COPY patches/release12/app/styles.css /app/app/styles.css
COPY patches/release12/tests/backlog12.test.ts /app/tests/backlog12.test.ts
COPY patches/release12/tests/feedback-ui.mjs /app/tests/feedback-ui.mjs
COPY patches/release12/tests/generation.test.ts /app/tests/generation.test.ts
COPY patches/release12/tests/indexation12.test.ts /app/tests/indexation12.test.ts
COPY patches/release12/extensions/rankpilot-schema/blocks/rankpilot.liquid /app/extensions/rankpilot-schema/blocks/rankpilot.liquid
RUN npm ci && npx prisma generate && npm run build
ENV NODE_ENV=production
ENV DATABASE_URL=file:/data/rankpilot.sqlite
RUN mkdir -p /data && chown -R node:node /data /app
USER node
EXPOSE 3000
CMD ["sh", "-c", "npm run setup && npm run start:all"]
