import {useState} from 'react';
import {Link} from 'react-router';
import type {pageSuggestions} from '../core/suggestions.server';
type Plan=Awaited<ReturnType<typeof pageSuggestions>>;
export function SourceSuggestions({id,kind,plan,busy,onAction}:{id:string;kind:string;plan:Plan;busy:boolean;onAction:(intent:string,values:Record<string,string>)=>void}){
 const s=plan.suggestions;const [title,setTitle]=useState(s.title.value),[description,setDescription]=useState(s.summary.value),[confirmed,setConfirmed]=useState(false);
 return <section className="source-suggestions"><h3>{kind==='collection'?'Your collection improvement plan':'Suggestions from your existing page'}</h3><p>Start with the information already in Shopify. Check it, edit if needed, then review the before and after. Nothing is saved or published by opening this screen.</p>
 <label>Suggested Google title<input aria-label="Suggested Google title" value={title} maxLength={255} onChange={e=>setTitle(e.target.value)}/></label><small>{title===s.title.value?`${s.title.source} · ${s.title.confidence}`:"Edited by you — check it against your source"}</small>
 <label>Suggested Google summary<textarea aria-label="Suggested Google summary" value={description} maxLength={500} onChange={e=>setDescription(e.target.value)}/></label><small>{description!==s.summary.value?"Edited by you — check it against your source":s.summary.value?`${s.summary.source} · ${s.summary.confidence}`:'No suitable complete statement found. Add a summary using information you have checked.'}</small>
 <label className="check-row"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked this wording against the product or page information</label>
 <button type="button" className="button primary" disabled={busy||!confirmed||!title.trim()||!description.trim()} onClick={()=>onAction('saveSourceDraft',{id,title,description,confirmed:'yes'})}>Review this Google listing</button>
 <details><summary>Source wording, details and suggested questions</summary><p>These are extracted suggestions, not independently verified specifications. Existing entries are retained. Confirm facts below before using FAQ answers.</p><ul>{s.features.map((v,i)=><li key={i}>{v} <small>Current description · medium confidence</small></li>)}</ul>{s.faqs.map(f=><p key={f.question}><b>{f.question}</b><br/>{f.answer}<br/><small>{f.source} · needs confirmation</small></p>)}{s.alts.map(a=><p key={a.id}>Image: {a.value||'No description yet'} · {a.source}</p>)}{!s.faqs.length&&<p>No labelled specifications found for FAQ answers. Add checked facts below or use a supplier spreadsheet.</p>}</details>
 <details open={kind==='collection'}><summary>Suggested search phrases</summary><p><b>{s.primary}</b> · {plan.keywordSource} Use a phrase that accurately describes this page.</p>{s.secondary.length>0?<p>Also consider: {s.secondary.join(' · ')}. {plan.keywordSource}</p>:<p>No additional source-backed phrases found yet.</p>}</details>
 {plan.collection&&<><h3>Build out this collection</h3><p>A keyword alone is not a complete page. Give shoppers an accurate introduction and clear routes to the products. We add only supported content; an arbitrary word count is not a ranking guarantee.</p><button type="button" className="button" disabled={busy||!plan.collection.children.length} onClick={()=>onAction('collectionCopy',{id})}>Review introduction and product guide</button><p>{plan.collection.count} products in the imported collection. The guide selects up to five products that match the collection topic and keeps the existing description.</p><details><summary>Collection address and structured data</summary><p>Suggested address based on your saved phrase: /collections/{plan.collection.handle}. A stable, useful address is usually worth keeping. Use the page-address preview in the catalogue toolbar only when a change is necessary; Shopify creates a redirect from the old address.</p><p>Breadcrumb and ItemList coverage are checked in the schema inventory. Existing theme markup takes priority. Missing markup needs the RankPilot theme embed or a theme update; accepting copy does not silently change your theme.</p><Link to="/app/aeo">Inspect structured-data coverage →</Link></details></>}
 <details><summary>Relevant links and incoming routes</summary><p>{plan.incoming.count} other editable page descriptions currently link here. This covers imported body content; navigation and theme links are outside this count.</p>{plan.links.map(l=><p key={l.id}><b>{l.title}</b> · {l.impact} priority: {l.reason}</p>)}{plan.links.length>0&&<button type="button" className="button" disabled={busy} onClick={()=>onAction('optimise',{ids:JSON.stringify([id]),feature:'links'})}>Prepare relevant links to review</button>}{!plan.links.length&&<p>No strong new commercial matches. Weak suggestions are omitted.</p>}{plan.incoming.count===0&&<p>No incoming links were found in imported descriptions. Relevant source pages below can add a route to this page.</p>}{plan.incoming.suggestions.map(r=><div className="source-link" key={r.id}><p><b>{r.title}</b> · {r.impact} priority: {r.reason}</p><button type="button" className="button" disabled={busy} onClick={()=>onAction('linkIntoPage',{id:r.id,targetId:id})}>Review an incoming link</button></div>)}</details>
 </section>;
}
