import {useFetcher} from 'react-router';
import {speedRecommendations,speedGuidance,fieldMeasurement,type SpeedResult} from '../core/performance';
export function PageSpeedResults({domain,metrics,jobs,demo}:{domain:string;metrics:{provider:string;payload:string;period:string}[];jobs:{kind:string;status:string;error?:string|null}[];demo:boolean}){
 const f=useFetcher<{message?:string}>();const job=jobs.find(j=>j.kind==='pagespeed');const running=job&&['queued','running'].includes(job.status);const latest=new Map<string,SpeedResult>();
 for(const m of metrics.filter(m=>m.provider==='pagespeed').sort((a,b)=>b.period.localeCompare(a.period))){try{const v=JSON.parse(m.payload) as SpeedResult;if(!latest.has(v.url))latest.set(v.url,{...v,checkedAt:v.checkedAt||m.period});}catch{/* invalid legacy result */}}
 return <section className="card" id="page-speed"><h2>Page speed and customer experience</h2><p>Find what slows a mobile page down and what to do next.</p><details><summary>Why this matters and how to use it</summary><p>Test your homepage, a product and a collection. Google’s simulated mobile score is separate from real-user Core Web Vitals. Fix the largest measured opportunities first; saving a connection does not run a test.</p></details><f.Form method="post" className="inline-form"><input type="hidden" name="intent" value="pagespeed"/><input aria-label="Store page URL" name="url" type="url" required defaultValue={domain}/><button className="button primary" disabled={demo||!!running||f.state!=='idle'}>{running?'Testing page…':'Run mobile speed check'}</button></f.Form><p role="status">{f.data?.message}{running?' Google is measuring this page. Results will appear automatically.':job?.status==='failed'?` The test could not finish: ${job.error||'Please retry.'}`:''}</p>{!latest.size&&<p>No completed speed test yet. Your connection is ready to use once saved in Settings.</p>}
 {[...latest.values()].map(r=><article key={r.url}><h3>{r.url}</h3><p>{r.checkedAt?new Date(r.checkedAt).toLocaleString('en-GB'):''} · Mobile lab score: <strong>{typeof r.score==='number'?`${Math.round(r.score*100)}/100`:'Unavailable'}</strong></p>{r.error&&<p role="alert">{r.error}</p>}<h4>Real-user measurements</h4>{r.field?.metrics?Object.entries(r.field.metrics).map(([k,v])=><p key={k}>{fieldMeasurement(k,v.percentile)} · {v.category||'Not classified'}</p>):<p>Not enough real-user data reported. This is not a passing result.</p>}<h4>What to improve next</h4>{speedRecommendations(r).slice(0,8).map(a=><details key={a.id}><summary>{a.title} {a.displayValue?`— ${a.displayValue}`:''}</summary><p>{speedGuidance(a.id)}</p><p>{a.details?.overallSavingsMs?`Estimated saving in this test: ${Math.round(a.details.overallSavingsMs)} ms.`:''}</p></details>)}{!speedRecommendations(r).length&&<p>No prioritised opportunities were returned in this test. Inspect the full report for other diagnostics.</p>}<a href={`https://pagespeed.web.dev/analysis?url=${encodeURIComponent(r.url)}&form_factor=mobile`} target="_blank" rel="noreferrer">Open Google’s detailed test</a></article>)}
 </section>;
}
