import {useState} from 'react';
import {Link,useFetcher} from 'react-router';
import {pageGains,queryTotals,canonicalPage,clickRate,metricPair,type SearchRow} from '../core/analytics';
import {providerMessage} from '../core/provider-health';
import type {loadUI} from '../core/ui.server';
type Data=Awaited<ReturnType<typeof loadUI>>;
function Pager({page,setPage,count}:{page:number;setPage:(p:number)=>void;count:number}){return <div className="report-pages"><span>{count?`${page*15+1}–${Math.min(count,(page+1)*15)} of ${count}`:'No matching rows'}</span><button className="button" disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><button className="button" disabled={(page+1)*15>=count} onClick={()=>setPage(page+1)}>Next</button></div>;}
export function SearchPerformance({metrics}:{metrics:Data['metrics']}){
 const [page,setPage]=useState(0),[queryPage,setQueryPage]=useState(0),[mode,setMode]=useState('gains');
 const [current,previous]=metricPair(metrics,'gsc');const queries=queryTotals(current?.rows);
 const gains=pageGains(current,previous).filter(r=>mode==='all'||r.change!==null&&r.change>0);
 const within=queries.filter(r=>r.impressions>=10&&r.position!==undefined&&r.position>=8&&r.position<=20).sort((a,b)=>b.impressions-a.impressions);
 const best=(url:string)=>queries.filter(r=>r.keys[0]===url&&r.impressions>=10&&r.position!==undefined).sort((a,b)=>a.position!-b.position!)[0];
 return <><section className="card"><h2>{mode==='gains'?'Pages getting more search visits':'Page search performance'}</h2><p>Google Search Console · {current?.start||'Not connected'}{current?.end?` to ${current.end}`:''}. Product variants and tracking URLs are grouped. Average positions are reported observations, not a live rank check. Country: all; device: all. Positions below 10 impressions are hidden. Property: {current?.property||'stored Search Console connection'}.</p><label>Show pages<select value={mode} onChange={e=>{setMode(e.target.value);setPage(0);}}><option value="gains">Only pages with more clicks</option><option value="all">All reported pages</option></select></label>{!previous&&mode==='gains'&&<p>A previous reporting period is needed to identify gains. Choose all reported pages to see current evidence.</p>}<table className="report-table"><thead><tr><th>Page</th><th>Clicks</th><th>Views</th><th>Average position</th><th>Best reported query</th><th>Click change</th></tr></thead><tbody>{gains.slice(page*15,page*15+15).map(r=>{const q=best(r.url);return <tr key={r.url}><td>{r.url}</td><td>{r.clicks}</td><td>{r.impressions}</td><td>{r.impressions>=10?r.position.toFixed(1):'Too few impressions'}</td><td>{q?`${q.keys[1]||'Query unavailable'} · position ${q.position!.toFixed(1)} · ${q.impressions} views`:'Not reported'}</td><td>{r.change===null?'No baseline':`${r.change>0?'+':''}${r.change}`}</td></tr>;})}</tbody></table><Pager page={page} setPage={setPage} count={gains.length}/></section>
 <section className="card"><h2>Searches within reach</h2><p>Real searches at average positions 8–20. Click rate is clicks divided by views. Different queries can place the same page very differently.</p><table className="report-table"><thead><tr><th>Search phrase and page</th><th>Views in search</th><th>Clicks</th><th>Position</th><th>Click rate</th></tr></thead><tbody>{within.slice(queryPage*15,queryPage*15+15).map((r:SearchRow)=><tr key={r.keys.join('|')}><td><strong>{r.keys[1]}</strong> <a href={`https://www.google.co.uk/search?q=${encodeURIComponent(r.keys[1])}`} target="_blank" rel="noreferrer">Check this live ↗</a><br/><small>{r.keys[0]}</small></td><td>{r.impressions}</td><td>{r.clicks}</td><td>{r.position?.toFixed(1)}</td><td>{clickRate(r.clicks,r.impressions)}</td></tr>)}</tbody></table><Pager page={queryPage} setPage={setQueryPage} count={within.length}/></section></>;
}
export function ConnectionActivity({d}:{d:Data}){return <section className="card"><h2>Connection activity</h2>{d.events.filter(e=>/failed|unavailable/.test(e.message)||JSON.parse(e.detail).errors?.length).slice(0,6).map(e=>{const detail=JSON.parse(e.detail);return <div key={e.id}><h3>{e.message.replace('openai','OpenAI').replace('AI sample failed:','AI sampling unavailable:')}</h3><p>{providerMessage(detail.error||detail.message||detail.errors?.join(' '))}</p><small>{new Date(e.createdAt).toLocaleString('en-GB')}</small></div>;})}<p>Successful service requests confirm access. Failed requests are not counted as answers or a zero score.</p><Link className="button" to="/app/settings">Check connections</Link></section>;}
export function MerchantFeed({d,onDetails}:{d:Data;onDetails:(id:string)=>void}){
 const refresh=useFetcher<{message:string}>();const [page,setPage]=useState(0);const feed=metricPair(d.metrics,'merchant')[0];
 const products=(feed?.products||[]) as {name:string;offerId:string;title?:string;link?:string;missing:string[];coverage?:Record<string,string>}[];
 if(products.length && feed?.mappingVersion!==3)return <section className="card"><h2>Google Shopping details</h2><p>Refresh these details to load product names and the current barcode fields. Older imports may have incorrectly listed existing details as missing.</p><refresh.Form method="post" action="/app?index" preventScrollReset><input type="hidden" name="intent" value="analytics"/><button className="button" disabled={refresh.state!=='idle'}>{refresh.state==='idle'?'Refresh Shopping details':'Queuing refresh…'}</button></refresh.Form>{refresh.data&&<p role="status">{refresh.data.message}</p>}</section>;
 const issues=products.filter(p=>p.missing.length);const coverageKeys=["gtin","brand","price","availability","condition","shipping","returns"];
 const names:Record<string,string>={gtin:'Manufacturer barcode',brand:'Brand name',productTypes:'Product category',shipping:'Delivery information — check account-level settings too'};
 return <section className="card"><h2>Google Shopping details to review</h2>{products.length>0&&<details><summary>Completeness by product property</summary><p>These are fields present in the imported Shopping feed, not independently confirmed facts. Shipping and returns can be configured at account level; missing item-level values are not automatically failures.</p><table><thead><tr><th>Property</th><th>Present in feed</th><th>Exempt or account check</th></tr></thead><tbody>{coverageKeys.map(k=><tr key={k}><th>{k}</th><td>{products.filter(p=>["present","label-present"].includes(p.coverage?.[k]||"")).length} / {products.length}</td><td>{products.filter(p=>["exempt","account-check"].includes(p.coverage?.[k]||"")).length}</td></tr>)}</tbody></table></details>}<p>{products.length?`${issues.length} of ${products.length} Shopping items need a detail checked.`:'Connect Merchant Center and refresh analytics to check Shopping listings.'} A barcode is only appropriate when the manufacturer has assigned one. Missing item-level delivery details may already be covered by your account settings. Update barcode, brand and category in Shopify or your feed source; checked facts in RankPilot do not edit your Shopping feed.</p>{issues.slice(page*15,page*15+15).map(p=>{const r=d.resources.find(r=>p.link&&canonicalPage(p.link).endsWith(`/products/${r.handle}`));return <div className="mini-stat" key={p.name}><div><strong>{p.title||r?.title||'Shopping listing awaiting product match'}</strong><p>{p.missing.map(k=>names[k]||k).join(' · ')}</p></div>{r&&<button className="button" onClick={()=>onDetails(r.id)}>Review source details</button>}<a className="button" href="https://merchants.google.com/" target="_blank" rel="noreferrer">Review in Merchant Center</a></div>;})}<Pager page={page} setPage={setPage} count={issues.length}/></section>;
}
