import {useState} from 'react';
import {useFetcher,Link} from 'react-router';
export function TechnicalTools({discoveries}:{discoveries:Record<string,unknown>}){
 const f=useFetcher<{message:string;changeId?:string}>();const [urls,setUrls]=useState('');const [error,setError]=useState('');const [oldPath,setOldPath]=useState('');
 const reported=(Array.isArray(discoveries.reported)?discoveries.reported:[]) as {path:string;status:number|null;state:string}[];
 const schemas=(Array.isArray(discoveries.schemas)?discoveries.schemas:[]) as {url:string;types:(string|string[])[];valid?:boolean}[];
 const families=[['Products','/products/',['Product','Offer']],['Collections','/collections/',['BreadcrumbList']],['Blogs','/blogs/',['Article','BreadcrumbList']]] as const;
 return <section className="card" id="technical-tools"><h2>Missing pages and search-engine checks</h2><details open><summary>Import missing URLs from another tool</summary><p>A crawler cannot discover every retired address. Upload an Avada export or paste one store path per line. Imported addresses are checked on each audit. Cart and checkout actions are excluded.</p><input type="file" accept=".csv,text/csv" aria-label="Import missing URL CSV" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>500000){setError('Choose a CSV smaller than 500 KB.');return;}setUrls(await file.text());setError('');}}/><f.Form method="post"><input type="hidden" name="intent" value="importMissingUrls"/><label>CSV contents or page paths<textarea name="urls" value={urls} onChange={e=>setUrls(e.target.value)} required rows={4}/></label><button className="button" disabled={f.state!=='idle'}>Import and check URLs</button></f.Form>{error&&<p role="alert">{error}</p>}</details>
 <details open><summary>Imported old addresses: redirect or remove</summary><p>A missing address has no live page left to delete. Remove it from this tracking list if you no longer need to monitor it, or prepare a redirect to a relevant working page. Removing it here does not remove links on other sites or erase it from search engines.</p><div className="table-wrap"><table><thead><tr><th>Old address</th><th>Current result</th><th>Action</th></tr></thead><tbody>{reported.map(r=><tr key={r.path}><td>{r.path}</td><td>{r.state}{r.status?` (${r.status})`:''}</td><td>{[404,410].includes(r.status||0)&&<button className="button" onClick={()=>{setOldPath(r.path);document.getElementById('prepare-redirect')?.setAttribute('open','');document.getElementById('prepare-redirect')?.scrollIntoView({behavior:'smooth'});}}>Redirect to another page</button>}<f.Form method="post"><input type="hidden" name="intent" value="removeReportedUrl"/><input type="hidden" name="path" value={r.path}/><button className="button" disabled={f.state!=='idle'}>Remove from tracking</button></f.Form></td></tr>)}</tbody></table></div>{!reported.length&&<p>Import an export and complete a scan to see current results here.</p>}</details>
 <details id="prepare-redirect"><summary>Forward an old address to a relevant page</summary><p>The homepage is selected by default. Choose a relevant replacement where available. Apply update checks the addresses, saves your redirect and verifies it.</p><f.Form method="post" className="inline-form"><input type="hidden" name="intent" value="applyRedirect"/><label>Old path<input name="path" value={oldPath} onChange={e=>setOldPath(e.target.value)} placeholder="/products/retired-product" required/></label><label>Replacement path<input name="target" defaultValue="/" placeholder="/" required/></label><button className="button" disabled={f.state!=='idle'}>{f.state!=='idle'?'Applying update…':'Apply update'}</button></f.Form><p>Saved changes and undo are available in <Link to="/app/reports">Results &amp; history</Link>.</p></details>
 {f.data&&<p role="status">{f.data.message}</p>}
 <details><summary>Structured data coverage</summary><p>Coverage of required types on scanned page families, not every theme template or a Google eligibility guarantee. Existing theme/app schema is inspected before adding anything.</p>{families.map(([name,path,required])=>{const pages=schemas.filter(s=>new URL(s.url).pathname.includes(path));const complete=pages.filter(s=>required.every(t=>s.types.flat().includes(t))&&s.valid!==false);return <p key={name}>{name}: {pages.length?`${Math.round(100*complete.length/pages.length)}% · ${complete.length}/${pages.length} scanned pages contain ${required.join(' and ')} without detected schema errors`:'Not checked'}</p>})}<p>Ratings, reviews and GTINs must come from real product data. FAQ markup requires visible matching answers.</p></details>
 <p><Link to="/app/reports#page-speed">View page speed results and recommendations →</Link></p>
 </section>;
}
