import {shopifyScript} from './shopify-sdk.mjs';
// Local demo-only regression test. Never opens Shopify or uses production credentials.
import {spawn} from 'node:child_process';
import {createCipheriv,randomBytes} from 'node:crypto';
import {setTimeout as wait} from 'node:timers/promises';
import {chromium,expect} from '@playwright/test';
import portable from '@sparticuz/chromium';
import {mkdirSync,writeFileSync,readFileSync,chmodSync,existsSync} from 'node:fs';
import {brotliDecompressSync} from 'node:zlib';
import {spawnSync} from 'node:child_process';
import {createCookie} from 'react-router';
import {PrismaClient} from '@prisma/client';
const env={...process.env,DEMO_MODE:'true',DATABASE_URL:'file:/tmp/rankpilot-feedback6.sqlite',SHOPIFY_APP_URL:'http://localhost:3016',ENCRYPTION_KEY:'a'.repeat(64),SHOPIFY_API_KEY:'local-test-key',PORT:'3016',HOST:'127.0.0.1'};
const migration=spawnSync('node',['node_modules/prisma/build/index.js','migrate','deploy'],{env,encoding:'utf8'});
if(migration.status!==0)throw new Error(migration.stderr||migration.stdout);
const db=new PrismaClient({datasources:{db:{url:env.DATABASE_URL}}});
const server=spawn('node',['./node_modules/@react-router/serve/bin.js','./build/server/index.js'],{env,stdio:['ignore','pipe','pipe']});
let logs='';server.stdout.on('data',d=>logs+=d);server.stderr.on('data',d=>logs+=d);
let browser;
try {
 for(let i=0;i<60;i++){try{if((await fetch('http://localhost:3016/health')).ok)break;}catch{}await wait(250);if(i===59)throw new Error(logs);}
 const runtime=process.cwd()+'/.browser-runtime';mkdirSync(runtime,{recursive:true});
 const executablePath=runtime+'/chromium';
 if(!existsSync(executablePath)){writeFileSync(executablePath,brotliDecompressSync(readFileSync('node_modules/@sparticuz/chromium/bin/chromium.br')));chmodSync(executablePath,0o755);}
 for(const name of ['fonts','swiftshader']){const target=name==='fonts'?runtime+'/fonts':runtime;mkdirSync(target,{recursive:true});const tar=runtime+'/'+name+'.tar';writeFileSync(tar,brotliDecompressSync(readFileSync('node_modules/@sparticuz/chromium/bin/'+name+'.tar.br')));spawnSync('tar',['--no-same-owner','-xf',tar,'-C',target]);}
 writeFileSync(runtime+'/fonts/fonts.conf',`<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "fonts.dtd"><fontconfig><dir>${runtime}/fonts/fonts</dir><dir>/usr/share/fonts</dir><cachedir>${runtime}/font-cache</cachedir></fontconfig>`);
 process.env.FONTCONFIG_PATH=runtime+'/fonts';process.env.LD_LIBRARY_PATH=runtime;
 browser=await chromium.launch({executablePath,args:portable.args.filter(a=>!a.includes('disable-web-security')),headless:true});
 const context=await browser.newContext();const page=await context.newPage();page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.context().route('https://cdn.shopify.com/shopifycloud/polaris.js',async r=>r.fulfill({contentType:'text/javascript',body:await shopifyScript('polaris')}));
 await page.goto('http://localhost:3016/app/audit');
 const type=page.getByLabel('Filter finding type');await type.selectOption('missing-alt');
 await expect(type).toHaveValue('missing-alt');
 await page.reload();await expect(type).toHaveValue('missing-alt');
 const rows=page.locator('table').filter({has:page.getByRole('columnheader',{name:'Page & finding',exact:true})}).locator('tbody tr');
 expect(await rows.count()).toBeGreaterThan(0);
 for(const row of await rows.all())await expect(row).toContainText('One or more images have no description');
 console.log('PASS finding filter applies and survives reload');
 // Change a queued job to completed from outside the page. No navigation/reload.
 const cookie=(await page.context().cookies()).find(c=>c.name==='rankpilot_demo');
 const storeId=await createCookie('rankpilot_demo',{secrets:[env.SESSION_SECRET || 'local-demo-only']}).parse('rankpilot_demo='+cookie.value);
 const store=await db.store.findUniqueOrThrow({where:{id:storeId}});

 const cfg=JSON.parse(store.settings);cfg.reportedPaths=['/products/retired-fixture'];
 await db.store.update({where:{id:store.id},data:{settings:JSON.stringify(cfg),discoveries:JSON.stringify({reported:[{path:'/products/retired-fixture',status:404,state:'Missing page'}]})}});
 await page.reload();
 await page.getByRole('button',{name:'Redirect to another page',exact:true}).click();
 await expect(page.getByRole('textbox',{name:'Old path',exact:true})).toHaveValue('/products/retired-fixture');
 await page.getByRole('button',{name:'Remove from tracking',exact:true}).click();
 await expect(page.getByText('Removed from tracking. No Shopify page or redirect was deleted.',{exact:false})).toBeVisible();
 await expect(page.getByRole('button',{name:'Remove from tracking',exact:true})).toHaveCount(0);
 expect(JSON.parse((await db.store.findUniqueOrThrow({where:{id:store.id}})).settings).reportedPaths).toEqual([]);
 console.log('PASS old URL redirect selection and removal from tracking');
 const job=await db.job.create({data:{storeId:store.id,kind:'audit',status:'running',dedup:crypto.randomUUID(),payload:'{}'}});
 await expect(page.getByText('Latest audit job: running')).toBeVisible({timeout:20000});
 await db.job.update({where:{id:job.id},data:{status:'completed',payload:JSON.stringify({result:{score:80}})}});
 await expect(page.getByText('Latest audit job: completed')).toBeVisible({timeout:15000});
 console.log('PASS external job completion appears without refresh');
 const product=await db.resource.findFirstOrThrow({where:{storeId:store.id,kind:'product'}});
 await db.resource.update({where:{id:product.id},data:{facts:'{}'}});
 await page.goto('http://localhost:3016/app/products');
 await page.getByLabel('CSV contents').fill(`handle,materials,source\n${product.handle},Steel,Local supplier fixture`);
 await page.getByRole('button',{name:'Preview import',exact:true}).click();
 await expect(page.getByText(/Matched 1 products/)).toBeVisible();
 await page.getByRole('button',{name:'Import unconfirmed facts',exact:true}).click();
 await expect(page.getByText(/Imported .*unconfirmed facts/)).toBeVisible();
 const saved=await db.resource.findUniqueOrThrow({where:{id:product.id}});
 const fact=JSON.parse(saved.facts).materials;
 if(fact.confirmed)throw new Error('Imported fact was incorrectly confirmed');
 console.log('PASS CSV preview and import retains unconfirmed source-backed fact');
 await db.change.createMany({data:[{storeId:store.id,resourceId:product.id,feature:'seo',before:'{}',after:JSON.stringify({title:'Camping mug',description:'A camping mug.'}),reasons:JSON.stringify(['source-reviewed-v1: Current review']),blockers:'[]'},{storeId:store.id,resourceId:product.id,feature:'seo',before:'{}',after:JSON.stringify({title:'Old mug',description:'An older mug.'}),reasons:JSON.stringify(['source-reviewed-v1: The existing Shopify page title is reused']),blockers:'[]'}]});
 await page.goto('http://localhost:3016/app/reviews');
 await expect(page.getByRole('button',{name:'Ready to accept (1)',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Needs attention (1)',exact:true})).toBeVisible();
 console.log('PASS ready and blocked review counts are separate');
 await page.goto('http://localhost:3016/app');
 await expect(page.getByRole('navigation',{name:'Main navigation'}).getByRole('link')).toHaveCount(3);
 await page.getByRole('button',{name:'Review ready fixes (1)',exact:true}).click();
 await expect(page.locator('dialog.change-preview')).toBeVisible();
 await expect(page.locator('dialog.change-preview').getByRole('button',{name:'Before',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Close preview',exact:true}).click();
 await page.getByRole('button',{name:'Review as a set',exact:true}).click();
 console.log('PASS Review ready fixes opens the first preview immediately');
 const batchResource=await db.resource.findFirstOrThrow({where:{storeId:store.id,id:{not:product.id}}});
 const rejectInSet=await db.change.create({data:{storeId:store.id,resourceId:batchResource.id,feature:'seo',before:'{}',after:JSON.stringify({title:'Review then decline',description:'A fixture summary.'}),reasons:JSON.stringify(['source-reviewed-v1: Current review']),blockers:'[]'}});
 await page.reload();await page.getByRole('button',{name:'Review as a set',exact:true}).click();
 await page.getByText('How your page looks on Google — 2 ready',{exact:true}).click();
 const setCard=page.locator('section.card').filter({has:page.getByRole('heading',{name:'Review similar improvements together',exact:true})});
 const declined=setCard.locator('details').filter({has:page.locator('summary').filter({hasText:batchResource.title})}).last();
 await declined.locator('summary').first().click();
 await declined.getByRole('button',{name:'Reject this suggestion',exact:true}).click();
 await expect(page.getByText('How your page looks on Google — 1 ready',{exact:true})).toBeVisible();
 expect((await db.change.findUniqueOrThrow({where:{id:rejectInSet.id}})).status).toBe('rejected');
 console.log('PASS individual rejection inside a batch removes only that suggestion');

 const batchButton=page.getByRole('button',{name:'Accept and apply this set (1)',exact:true});
 await expect(batchButton).toBeDisabled();
 await page.getByLabel('I approve this 1 preview.').check();
 await batchButton.click();
 await expect(page.getByText(/1 changes accepted and queued to save/)).toBeVisible();
 expect(await db.change.count({where:{storeId:store.id,status:'approved'}})).toBe(1);
 expect(await db.change.count({where:{storeId:store.id,status:'pending'}})).toBe(1);
 console.log('PASS explicit batch approval excludes blocked drafts');

 await page.goto('http://localhost:3016/app');
 await expect(page.getByRole('heading',{name:'Fix these next',exact:true})).toBeVisible();
 await expect(page.locator('.dashboard-metrics .metric')).toHaveCount(4);
 await expect(page.locator('.catalogue-tiles a')).toHaveCount(3);
 await page.screenshot({path:'/tmp/rankpilot-dashboard8.png',fullPage:true});
 console.log('PASS dashboard metrics, priority actions and content navigation');
 await page.goto('http://localhost:3016/app/settings');
 await expect(page.getByLabel('Brand suffix')).toBeVisible();
 const voice=page.locator('textarea[name="brandVoice"]');
 await voice.fill('Warm, clear British English. Keep our original stories.');
 await expect(voice).toHaveValue('Warm, clear British English. Keep our original stories.');
 await wait(5500);
 await expect(voice).toHaveValue('Warm, clear British English. Keep our original stories.');
 console.log('BRAND FIELD',await voice.evaluate(e=>({disabled:e.disabled,readOnly:e.readOnly,background:getComputedStyle(e).backgroundColor})));
 console.log('PASS brand voice accepts typing and survives background polling');
 await page.getByLabel('Brand suffix').selectOption('omit');
 await page.getByRole('button',{name:'Save settings',exact:true}).click();
 await expect(page.getByText('Settings saved.',{exact:false})).toBeVisible().catch(async()=>{const cfg=JSON.parse((await db.store.findUniqueOrThrow({where:{id:store.id}})).settings);expect(cfg.titleBrandMode).toBe('omit');});
 // Simulate the embedded branch in an iframe. Shopify is not contacted: a
 // local ID-token stub and request guard exercise the production client path.
 const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',Buffer.from(env.ENCRYPTION_KEY,'hex'),iv);
 const encrypted=Buffer.concat([cipher.update(JSON.stringify({openaiKey:'local-unused-fixture'}),'utf8'),cipher.final()]);
 const fixtureCredential=['v1',iv.toString('base64'),cipher.getAuthTag().toString('base64'),encrypted.toString('base64')].join('.');
 await db.store.update({where:{id:store.id},data:{demo:false,credentials:fixtureCredential}});
 await page.context().addInitScript(()=>{window.shopify={idToken:async()=> 'local-embedded-test-token'};});
 await page.context().route('https://cdn.shopify.com/shopifycloud/app-bridge.js',r=>r.fulfill({contentType:'text/javascript',body:''}));
 let failedStatus=true,authenticatedPolls=0;
 await page.context().route('**/app/job-status',r=>{
   if(r.request().headers().authorization!=='Bearer local-embedded-test-token')return r.fulfill({status:401,body:'Missing authentication'});
   authenticatedPolls++;
   if(failedStatus)return r.fulfill({status:503,body:'Temporary outage'});
   return r.continue();
 });
 // The real app permits only Shopify frame ancestors. This fixture uses a
 // local parent, so remove that header from the local test response only.
 await page.context().route('http://localhost:3016/app/audit',async r=>{
   const response=await r.fetch();const headers={...response.headers()};
   delete headers['content-security-policy'];delete headers['x-frame-options'];
   await r.fulfill({response,headers});
 });
 await page.context().route('http://localhost:3016/test-frame',r=>r.fulfill({contentType:'text/html',body:'<iframe title="Local embedded app" src="http://localhost:3016/app/audit" style="width:1500px;height:1000px"></iframe>'}));
 await page.goto('http://localhost:3016/test-frame');
 const frame=page.frameLocator('iframe');
 await expect(frame.getByText(/Live progress is temporarily unavailable/)).toBeVisible({timeout:15000});
 const embedFilter=frame.getByLabel('Filter finding type');
 await embedFilter.selectOption('missing-alt');await expect(embedFilter).toHaveValue('missing-alt');
 failedStatus=false;
 await expect(frame.getByText(/Live progress is temporarily unavailable/)).toHaveCount(0,{timeout:15000});
 // Start a real generation request, then supply the worker result in this
 // isolated database. No AI or Shopify writes are involved.
 await frame.getByRole('button',{name:'Generate fix',exact:true}).first().click();
 let generated;
 for(let i=0;i<30;i++){generated=await db.job.findFirst({where:{storeId:store.id,kind:'optimise'},orderBy:{createdAt:'desc'}});if(generated)break;await wait(100);}
 if(!generated)throw new Error('Generation request not enqueued');
 const payload=JSON.parse(generated.payload);const rid=payload.ids[0];
 const change=await db.change.create({data:{storeId:store.id,resourceId:rid,feature:'alt',before:JSON.stringify([{id:'fixture-image',alt:''}]),after:JSON.stringify([{id:'fixture-image',alt:'A camping mug on a table.'}]),reasons:JSON.stringify(['image-reviewed-v1: local fixture']),blockers:'[]'}});
 await db.job.update({where:{id:generated.id},data:{status:'completed',payload:JSON.stringify({...payload,result:[{resourceId:rid,changeId:change.id}]})}});
 await expect(frame.locator('dialog.change-preview')).toBeVisible({timeout:15000});
 await expect(frame.getByRole('button',{name:'Accept and apply',exact:true})).toBeEnabled();
 await frame.getByRole('button',{name:'Close preview',exact:true}).click();
 await expect(embedFilter).toHaveValue('missing-alt');
 if(authenticatedPolls<2)throw new Error('Embedded polling did not authenticate');
 await db.store.update({where:{id:store.id},data:{demo:true}});
 console.log('PASS iframe filter, authenticated polling, outage recovery and generation completion without refresh');
 if(errors.length)throw new Error(errors.join('\n'));
 console.log('PASS metric and title preferences; no browser exceptions');
 // Reproduce reported usability paths against the real local React UI.
 await page.context().unroute('**/app/job-status');
 await page.goto('http://localhost:3016/app/settings');
 const savedVoice=page.getByLabel('Describe your brand’s tone');
 await expect(savedVoice).toHaveValue('Warm, clear British English. Keep our original stories.');
 expect(JSON.parse((await db.store.findUniqueOrThrow({where:{id:store.id}})).settings).brandVoice).toBe('Warm, clear British English. Keep our original stories.');
 console.log('PASS brand voice saved and reloads');
 await db.resource.createMany({data:Array.from({length:320},(_,i)=>({storeId:store.id,remoteId:'perf-'+i,kind:'product',title:'Performance fixture '+i,handle:'performance-'+i,payload:JSON.stringify({...JSON.parse(product.payload),images:[]})}))});
 await page.setViewportSize({width:1100,height:700});
 await page.goto('http://localhost:3016/app/products');
 const productRow=page.locator('tbody tr').filter({has:page.getByRole('checkbox',{name:'Select '+product.title,exact:true})});
 const selection=productRow.getByRole('checkbox');
 const selectedAt=Date.now();await selection.check();await expect(selection).toBeChecked({timeout:250});
 const selectionMs=Date.now()-selectedAt;expect(selectionMs).toBeLessThan(1000);console.log(`PASS selection confirmed in ${selectionMs}ms with 320 extra catalogue items`);
 await expect(page.getByText('1 selected',{exact:true})).toBeVisible({timeout:250});
 await productRow.getByRole('button',{name:'Product details',exact:true}).click();
 const factsModal=page.locator('dialog.facts-dialog');
 const saveFacts=factsModal.getByRole('button',{name:'Save product details',exact:true});
 await expect(saveFacts).toBeInViewport();
 const body=factsModal.locator('.facts-body');await body.hover();await page.mouse.wheel(0,1200);
 await expect.poll(()=>body.evaluate(e=>e.scrollTop)).toBeGreaterThan(0);
 await expect(saveFacts).toBeInViewport();
 await page.setViewportSize({width:390,height:700});await expect(saveFacts).toBeInViewport();
 await factsModal.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.setViewportSize({width:1100,height:700});
 console.log('PASS immediate selection feedback and modal wheel scrolling with visible Save/Cancel on desktop and mobile');
 // Delay receipt to prove progress is beside the clicked CTA, then complete the job externally.
 await page.route('**/app/products.data',async r=>{if(r.request().method()==='POST')await wait(800);await r.continue();});
 await page.getByRole('button',{name:'Generate previews',exact:true}).click();
 await expect(page.getByRole('button',{name:'Sending request…',exact:true})).toBeVisible();
 await expect(page.locator('.generation-feedback')).toContainText('Sending your request');
 await expect(page.getByRole('button',{name:'Preparing previews…',exact:true})).toBeVisible();
 const catalogueJob=await db.job.findFirstOrThrow({where:{storeId:store.id,kind:'optimise',status:'queued'},orderBy:{createdAt:'desc'}});
 const cataloguePayload=JSON.parse(catalogueJob.payload);
 const preview=await db.change.create({data:{storeId:store.id,resourceId:product.id,feature:'seo',before:JSON.stringify({title:'Original camping product',description:'Original summary.'}),after:JSON.stringify({title:'Camping product',description:'A useful sourced summary.'}),reasons:JSON.stringify(['source-reviewed-v1: Adds a specific description from the existing product information.']),blockers:'[]'}});
 await db.job.update({where:{id:catalogueJob.id},data:{status:'completed',payload:JSON.stringify({...cataloguePayload,result:[{resourceId:product.id,changeId:preview.id}]})}});
 const previewDialog=page.locator('dialog.change-preview');
 await expect(previewDialog).toBeVisible({timeout:15000});
 await expect(previewDialog.getByRole('heading',{name:'Why we suggest this',exact:true})).toBeVisible();
 await previewDialog.getByRole('button',{name:'Before',exact:true}).click();
 await expect(previewDialog.locator('.snippet')).toContainText('Original camping product');
 await previewDialog.getByRole('button',{name:'After',exact:true}).click();
 await expect(previewDialog.locator('.snippet')).toContainText('A useful sourced summary.');
 await previewDialog.getByRole('button',{name:'Close preview',exact:true}).click();
 console.log('PASS catalogue request receipt, running state and automatic reusable Before/After review');
 const latestAudit=await db.audit.findFirstOrThrow({where:{storeId:store.id},orderBy:{createdAt:'desc'}});
 const arenaIssues=[{resourceId:product.id,title:product.title,code:'missing-meta-description',severity:'critical',feature:'seo',detail:'The page needs a specific summary.'},{resourceId:'reported:/products/retired-test',title:'/products/retired-test',code:'reported-404',severity:'critical',detail:'Imported missing URL returns 404.'}];
 const arenaSettings=JSON.parse((await db.store.findUniqueOrThrow({where:{id:store.id}})).settings);arenaSettings.reportedPaths=['/products/retired-test'];
 await db.store.update({where:{id:store.id},data:{settings:JSON.stringify(arenaSettings)}});
 await db.audit.update({where:{id:latestAudit.id},data:{issues:JSON.stringify(arenaIssues)}});
 await page.goto('http://localhost:3016/app');
 await page.locator('.priority').filter({hasText:'Improve Google titles and summaries'}).getByRole('button').click();
 await expect(page).toHaveURL('http://localhost:3016/app');
 await expect(previewDialog.getByRole('heading',{name:'Why we suggest this',exact:true})).toBeVisible();
 await previewDialog.getByLabel('Reason for rejecting',{exact:true}).selectOption('Not relevant to this page');
 await previewDialog.getByRole('button',{name:'Reject',exact:true}).click();
 await expect(previewDialog.getByText('Rejected. Your current content has been kept.')).toBeVisible();
 expect((await db.change.findUniqueOrThrow({where:{id:preview.id}})).status).toBe('rejected');
 const rejectionEvent=await db.event.findFirstOrThrow({where:{storeId:store.id,message:'Change rejected'},orderBy:{createdAt:'desc'}});expect(JSON.parse(rejectionEvent.detail)).toMatchObject({resourceId:product.id,reason:'Not relevant to this page'});
 await previewDialog.getByRole('button',{name:'Close preview',exact:true}).click();
 await page.locator('.priority').filter({hasText:'Repair a reported missing page'}).getByRole('button').click();
 await expect(page).toHaveURL('http://localhost:3016/app');
 await expect(previewDialog.getByRole('textbox',{name:'Current broken URL',exact:true})).toHaveValue('/products/retired-test');
 await expect(previewDialog.getByRole('textbox',{name:'New target',exact:true})).toHaveValue('/');
 await previewDialog.getByLabel('Choose a working page').selectOption('/');
 await previewDialog.getByRole('button',{name:'Apply update',exact:true}).click();
 await expect(previewDialog.getByText('Done. Your shop has been updated.',{exact:true})).toBeVisible();
 const redirected=await db.change.findFirstOrThrow({where:{storeId:store.id,feature:'redirect',status:'applied'},orderBy:{createdAt:'desc'}});
 expect(JSON.parse(redirected.after)).toEqual({path:'/products/retired-test',target:'/'});
 expect(redirected.approvedBy).toBeTruthy();
 await previewDialog.getByRole('button',{name:'Close preview',exact:true}).click();
 await page.reload();
 const tiles=page.locator('.catalogue-tiles');await expect(tiles).toContainText('/100');await expect(tiles).not.toContainText('%');
 await page.locator('.priority').filter({hasText:'Repair a reported missing page'}).getByRole('button').click();
 await previewDialog.getByLabel('Choose a fix').selectOption('delete');
 await expect(previewDialog.getByText(/removes it from RankPilot tracking only/)).toBeVisible();
 await previewDialog.getByRole('button',{name:'Apply update',exact:true}).click();
 await expect(previewDialog.getByText(/Removed from tracking/)).toBeVisible();
 expect(JSON.parse((await db.store.findUniqueOrThrow({where:{id:store.id}})).settings).reportedPaths).toEqual([]);
 await previewDialog.getByRole('button',{name:'Close preview',exact:true}).click();
 console.log('PASS prefilled broken URL, explicit homepage fallback, direct approved/verified redirect, tracking deletion and /100 health tiles');
 const linkResource=await db.resource.findFirstOrThrow({where:{storeId:store.id,kind:'collection'}});
 const linkPayload=JSON.parse(linkResource.payload);linkPayload.descriptionHtml='<p><a href="/pages/dead-link">Keep this useful text</a> and <a href="/">Home</a></p>';
 await db.resource.update({where:{id:linkResource.id},data:{payload:JSON.stringify(linkPayload)}});
 const linkAudit=await db.audit.findFirstOrThrow({where:{storeId:store.id},orderBy:{createdAt:'desc'}});
 await db.audit.update({where:{id:linkAudit.id},data:{issues:JSON.stringify([{resourceId:linkResource.id,title:linkResource.title,code:'broken-link',severity:'warning',detail:`Link from ${store.domain}/collections/${linkResource.handle} to ${store.domain}/pages/dead-link returns 404.`}])}});
 await page.reload();
 await page.locator('.priority').filter({hasText:'Fix a broken link'}).getByRole('button').click();
 await expect(previewDialog.getByLabel('Current broken URL')).toHaveValue('/pages/dead-link');
 await previewDialog.getByLabel('Choose a fix').selectOption('delete');
 await previewDialog.getByRole('button',{name:'Apply update',exact:true}).click();
 await expect(previewDialog.getByText('Done. Your shop has been updated.',{exact:true})).toBeVisible();
 const updatedBody=JSON.parse((await db.resource.findUniqueOrThrow({where:{id:linkResource.id}})).payload).descriptionHtml;
 expect(updatedBody).toContain('Keep this useful text');expect(updatedBody).not.toContain('/pages/dead-link');expect(updatedBody).toContain('href="/"');
 await previewDialog.getByRole('button',{name:'Close preview',exact:true}).click();
 console.log('PASS delete applies an exact link removal and preserves text and unrelated links');

 // A shared dead collection is one root-cause ticket with restoration first.
 const rootCollection=await db.resource.create({data:{storeId:store.id,remoteId:'gid://shopify/Collection/9911',kind:'collection',title:'Summer festival essentials',handle:'summer-festival-essentials',payload:JSON.stringify({...linkPayload,title:'Summer festival essentials',handle:'summer-festival-essentials',productsCount:13})}});
 const liveCollection=await db.resource.create({data:{storeId:store.id,remoteId:'gid://shopify/Collection/9912',kind:'collection',title:'Summer camping equipment',handle:'summer-camping-equipment',payload:JSON.stringify({...linkPayload,title:'Summer camping equipment',handle:'summer-camping-equipment'})}});
 const referring=await db.resource.findMany({where:{storeId:store.id,kind:'product'},take:6});
 const dead=store.domain+'/collections/'+rootCollection.handle;
 await db.audit.update({where:{id:linkAudit.id},data:{issues:JSON.stringify(referring.map(r=>({resourceId:r.id,title:r.title,code:'broken-link',severity:'warning',detail:`Link from ${store.domain}/products/${r.handle} to ${dead} returns 404.`})))}});
 await db.store.update({where:{id:store.id},data:{discoveries:JSON.stringify({pages:[{url:store.domain+'/collections/'+liveCollection.handle,status:200}]})}});
 await page.goto('http://localhost:3016/app');
 const sharedTicket=page.locator('.priority').filter({hasText:'Fix a broken link'});await expect(sharedTicket).toHaveCount(1);await expect(sharedTicket).toContainText('6 affected pages');
 await sharedTicket.getByRole('button').click();
 await expect(previewDialog.getByRole('heading',{name:'Restore the existing page first'})).toBeVisible();await expect(previewDialog).toContainText('13 products');await expect(previewDialog).toContainText('6 referring pages');
 await expect(previewDialog.getByLabel('Choose a fix')).toHaveValue('restore');
 await previewDialog.getByLabel('Choose a fix').selectOption('redirect');await expect(previewDialog.getByLabel('New target',{exact:true})).toHaveValue('/collections/summer-camping-equipment');
 await previewDialog.getByRole('button',{name:'Close preview',exact:true}).click();
 await expect(page.locator('.search-score-grid').getByText('Technical health',{exact:true})).toBeVisible();await expect(page.locator('.search-score-grid').getByText('Google search visibility',{exact:true})).toBeVisible();await expect(page.locator('.dashboard-metrics').getByText('Discovery readiness',{exact:true})).toBeVisible();
 await page.screenshot({path:'/tmp/rankpilot11-dashboard.png',fullPage:true});
 console.log('PASS six symptoms grouped, existing collection restore guidance, ranked scanned target and separate scores');
 const acceptResource=await db.resource.findFirstOrThrow({where:{storeId:store.id,kind:'product',id:{not:product.id}}});
 const acceptPreview=await db.change.create({data:{storeId:store.id,resourceId:acceptResource.id,feature:'seo',before:JSON.stringify(JSON.parse(acceptResource.payload).seo),after:preview.after,reasons:preview.reasons,blockers:'[]'}});
 await page.reload();
 await page.getByRole('button',{name:/^Review ready fixes \(/}).click();
 const readySelect=previewDialog.getByLabel('Ready fix');
 expect(await readySelect.locator('option').count()).toBeGreaterThan(1);
 await previewDialog.getByRole('button',{name:'Next fix →',exact:true}).click();
 await expect(readySelect).toHaveValue('1');
 await previewDialog.getByRole('button',{name:'← Previous fix',exact:true}).click();
 await previewDialog.getByRole('button',{name:'Approve demo change',exact:true}).click();
 await expect(previewDialog.getByText(/Done\. Your suggested Google listing/)).toBeVisible();
 expect((await db.change.findUniqueOrThrow({where:{id:acceptPreview.id}})).status).toBe('applied');
 expect(JSON.parse((await db.resource.findUniqueOrThrow({where:{id:acceptResource.id}})).payload).seo).toEqual(JSON.parse(preview.after));
 await previewDialog.getByRole('button',{name:'Close preview',exact:true}).click();
 console.log('PASS ready-fix queue opens directly, navigates forward/back and accepts the exact preview');
 await db.metric.create({data:{storeId:store.id,provider:'gsc',period:'2026-09-01:2026-09-28',payload:JSON.stringify({start:'2026-09-01',end:'2026-09-28',rows:[{keys:['https://example.test/a','two clicks'],clicks:2,impressions:19,position:10},{keys:['https://example.test/b','zero clicks'],clicks:0,impressions:9,position:12},{keys:['https://example.test/c','tiny rate'],clicks:1,impressions:10000,position:15}]})}});
 await page.goto('http://localhost:3016/app/reports');
 const queries=page.locator('table').filter({has:page.getByRole('columnheader',{name:'Click rate',exact:true})});
 await expect(queries.locator('tr').filter({hasText:'two clicks'})).toContainText('10.5%');
 await expect(queries.locator('tr').filter({hasText:'zero clicks'})).toHaveCount(0); // fewer than 10 impressions: no ranking claim
 await expect(queries.locator('tr').filter({hasText:'tiny rate'})).toContainText('<0.1%');
 await expect(page.getByText('Google search clicks',{exact:true})).toBeVisible();
 await expect(page.getByText('Search-engine sessions',{exact:true})).toBeVisible();
 if(errors.length)throw new Error(errors.join('\n'));
 console.log('PASS real row-derived click rates, distinguishable sources and no browser errors');
 await db.store.update({where:{id:store.id},data:{credentials:'{}'}});
 await page.goto('http://localhost:3016/app/products');
 await page.getByRole('checkbox',{name:'Select '+product.title,exact:true}).check();
 await page.getByLabel('Improvement type').selectOption('alt');
 await page.getByRole('button',{name:'Generate previews',exact:true}).click();
 await expect(page.locator('.generation-feedback')).toContainText('Connect an OpenAI API key');
 await expect(page.getByRole('button',{name:'Generate previews',exact:true})).toBeEnabled();
 console.log('PASS generation failures appear beside the action and allow a corrected retry');

 const fresh=await db.resource.create({data:{storeId:store.id,remoteId:'gid://shopify/Product/991212',kind:'product',title:'Trail Ceramic Cup',handle:'trail-ceramic-cup',facts:'{}',payload:JSON.stringify({title:'Trail Ceramic Cup',handle:'trail-ceramic-cup',descriptionHtml:'<p>A ceramic cup with a blue glaze for the table.</p><p>Materials: Ceramic</p>',seo:{title:'',description:''},images:[],collections:[]})}});
 await page.goto('http://localhost:3016/app/products');
 const row=page.getByRole('row').filter({hasText:'Trail Ceramic Cup'});
 await row.getByRole('button',{name:'Product details',exact:true}).click();
 const sourceModal=page.locator('dialog.facts-dialog');
 await expect(sourceModal.getByLabel('Suggested Google title',{exact:true})).toHaveValue('Trail Ceramic Cup');
 await expect(sourceModal.getByLabel('Suggested Google summary',{exact:true})).toHaveValue('A ceramic cup with a blue glaze for the table.');
 await expect(sourceModal.locator('input[name="materials"]')).toHaveValue('Ceramic');
 await expect(sourceModal.locator('input[name="materialsConfirmed"]')).not.toBeChecked();
 await expect(sourceModal.locator('input[name="power"]')).toHaveValue('');
 await sourceModal.locator('input[name="materials"]').fill('');
 await sourceModal.locator('input[name="power"]').fill('Merchant text to preserve');
 await sourceModal.getByRole('button',{name:'Fill from existing product information',exact:true}).click();
 await expect(sourceModal.locator('input[name="materials"]')).toHaveValue('Ceramic');
 await expect(sourceModal.locator('input[name="power"]')).toHaveValue('Merchant text to preserve');
 await expect(sourceModal.locator('.fact-feedback')).toContainText('empty fields filled');
 expect(await sourceModal.locator('.facts-body').evaluate(e=>e.scrollTop)).toBeGreaterThan(50);
 await expect(sourceModal.locator('input[name="materialsConfirmed"]')).not.toBeChecked();
 await sourceModal.getByLabel('I checked this wording against the product or page information').check();
 await sourceModal.getByRole('button',{name:'Review this Google listing',exact:true}).click();
 await expect(sourceModal).not.toBeVisible();
 await expect(previewDialog).toBeVisible();
 await expect(previewDialog).toContainText('A ceramic cup with a blue glaze for the table.');
 await previewDialog.getByRole('button',{name:'Approve demo change',exact:true}).click();
 await expect(previewDialog.getByText(/Done\. Your suggested Google listing/)).toBeVisible();
 const appliedSource=await db.change.findFirstOrThrow({where:{storeId:store.id,resourceId:fresh.id,status:'applied'}});
 expect(await db.metric.count({where:{storeId:store.id,provider:'change-impact',period:appliedSource.id}})).toBe(1);
 expect(JSON.parse((await db.resource.findUniqueOrThrow({where:{id:fresh.id}})).payload).seo.title).toBe('Trail Ceramic Cup');
 await previewDialog.getByRole('button',{name:'Close preview',exact:true}).click();
 console.log('PASS auto-populated editable sourced listing, unconfirmed fact extraction, review/approve and saved impact baseline');
 // Compatibility aliases must resolve before rendering; unknown routes must not mimic a dashboard.
 for(const alias of ['blogs','articles']){await page.goto('http://localhost:3016/app/'+alias);await expect(page).toHaveURL('http://localhost:3016/app/content');}
 const unknown=await page.goto('http://localhost:3016/app/not-a-real-section');expect(unknown.status()).toBe(404);
 console.log('PASS blog aliases and unknown route handling');
 await page.addInitScript(()=>{window.__longTasks=[];new PerformanceObserver(list=>window.__longTasks.push(...list.getEntries().map(e=>e.duration))).observe({type:'longtask',buffered:true});});
 const rendererSamples=[];
 for(const width of [390,768,1024,1150,1290,1440]) {
  await page.setViewportSize({width,height:900});await page.goto('http://localhost:3016/app');
  await expect(page.getByRole('heading',{name:'Store Score',exact:true})).toBeVisible();
  await page.mouse.move(width-50,600);await page.mouse.wheel(0,700);
  await expect.poll(()=>page.evaluate(()=>document.scrollingElement.scrollTop)).toBeGreaterThan(100);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
  await page.evaluate(()=>{document.documentElement.style.overflow='hidden';document.body.style.overflow='hidden';});
  await page.locator('.workspace').focus();await page.keyboard.press('End');
  await expect.poll(()=>page.evaluate(()=>{const e=document.scrollingElement;return e.scrollTop+e.clientHeight>=e.scrollHeight-3;})).toBe(true);
  await page.getByRole('button',{name:/^Review ready fixes \(/}).click();await expect(previewDialog).toBeVisible();
  await previewDialog.getByRole('button',{name:'Close preview',exact:true}).click();
  await page.evaluate(()=>window.scrollTo(0,0));await page.mouse.move(width-50,600);await page.mouse.wheel(0,600);
  await expect.poll(()=>page.evaluate(()=>document.scrollingElement.scrollTop)).toBeGreaterThan(100);
  const tasks=await page.evaluate(()=>window.__longTasks||[]);const max=Math.max(0,...tasks);expect(max).toBeLessThan(2000);rendererSamples.push({width,maxLongTaskMs:Math.round(max)});
 }
 // Exercise long reporting tables and two simultaneous app tabs.
 await db.metric.create({data:{storeId:store.id,provider:'merchant',period:'2026-09-26',payload:JSON.stringify({mappingVersion:3,products:Array.from({length:61},(_,i)=>({name:'opaque-'+i,offerId:'internal-'+i,title:'Named Shopping product '+i,link:'https://example.test/products/'+fresh.handle,missing:['gtin','shipping']}))})}});
 const reportTab=await page.context().newPage();await reportTab.setViewportSize({width:1290,height:850});
 await reportTab.goto('http://localhost:3016/app/reports');
 const feedCard=reportTab.locator('section.card').filter({has:reportTab.getByRole('heading',{name:'Google Shopping details to review',exact:true})});
 await expect(feedCard.locator('.mini-stat')).toHaveCount(15);await expect(feedCard).not.toContainText('opaque-');
 await feedCard.getByRole('button',{name:'Next',exact:true}).click();await expect(feedCard).toContainText('16–30 of 61');
 const rateColumn=reportTab.getByRole('columnheader',{name:'Click rate',exact:true});await rateColumn.scrollIntoViewIfNeeded();
 const rateBounds=await rateColumn.boundingBox();expect(rateBounds.x+rateBounds.width).toBeLessThanOrEqual(1290);
 await expect(reportTab.locator('section.card').filter({has:reportTab.getByRole('heading',{name:'Pages getting more search visits',exact:true})}).getByRole('row')).toHaveCount(1);
 await reportTab.getByRole('combobox',{name:/^Show pages/}).selectOption('all');await expect(reportTab.getByRole('heading',{name:'Page search performance',exact:true})).toBeVisible();
 for(let i=0;i<3;i++)for(const tab of [page,reportTab]){const start=Date.now();await tab.locator('.workspace').focus();await tab.keyboard.press('PageDown');expect(Date.now()-start).toBeLessThan(2000);}
 expect(await page.evaluate(()=>PerformanceObserver.supportedEntryTypes.includes('longtask'))).toBe(true);
 await reportTab.close();console.log('PASS named/paginated Merchant listings, gain-only report, visible click-rate column and two-tab interaction');
 await page.setViewportSize({width:1440,height:1000});await page.goto('http://localhost:3016/app');
 await page.screenshot({path:'/tmp/rankpilot13-dashboard.png',fullPage:true});
 writeFileSync('/tmp/rankpilot13-browser-performance.json',JSON.stringify(rendererSamples,null,2));
 console.log('PASS responsive 390/768/1024/1150/1290/1440 layouts, wheel/End scrolling with locked host document, modal recovery and bounded renderer tasks',rendererSamples);

} catch(error) { console.error(logs); if(browser){for(const context of browser.contexts())for(const page of context.pages()){console.error(await page.locator("body").innerText());await page.screenshot({path:"/tmp/rankpilot10-browser-error.png"});}} throw error; } finally {await browser?.close();server.kill();await db.$disconnect();}
