import {useState} from 'react';
import {Link,useFetcher} from 'react-router';
import type {loadUI} from '../core/ui.server';
import {storeScore} from '../core/store-score';
import {metricPair} from '../core/analytics';
import {visibilityMethod,searchVisibility} from '../core/visibility-score';
import {fieldMeasurement,type SpeedResult} from '../core/performance';
type Data=Awaited<ReturnType<typeof loadUI>>;
function Tile({label,value,children,low=false}:{label:string;value:string;children:React.ReactNode;low?:boolean}){return <div className={'metric'+(low?' limited-evidence':'')}><div>{label}</div><strong>{value}</strong><details><summary>How this is measured / what to do</summary>{children}</details></div>;}
export function ScoreBoard({d}:{d:Data}){
 const [days,setDays]=useState(28);const check=useFetcher<{ok:boolean;message:string}>();
 const now=Date.parse(d.measuredAt),latest=d.audits[0];const score=storeScore({metrics:d.metrics,technical:latest?.score,healthScores:d.healthScores,observations:d.observations,now});
 const gsc=metricPair(d.metrics,'gsc')[0],ga=metricPair(d.metrics,'ga4')[0],ai=metricPair(d.metrics,'ga4-ai')[0];
 const history=d.metrics.filter(m=>m.provider==='store-score').map(m=>({...JSON.parse(m.payload),day:m.period})).filter(m=>m.version===score.version).sort((a,b)=>a.day.localeCompare(b.day));
 const baseline=history.filter(m=>Date.parse(m.day)<=now-days*86400000).at(-1);
 const delta=baseline?.score!=null&&score.score!==null?score.score-baseline.score:null;
 const trend=history.filter(m=>Date.parse(m.day)>=now-days*86400000&&m.score!==null);
 const money=(snapshot:typeof ga)=>snapshot?.rows?new Intl.NumberFormat('en-GB',{style:'currency',currency:snapshot.currency||'GBP'}).format(snapshot.rows.reduce((n:number,r:{metricValues?:{value:string}[]})=>n+Number(r.metricValues?.[1]?.value||0),0)):'Not measured';
 const n=(v:number|null|undefined)=>v==null?'Not measured':`${Math.round(v)}/100`;
 const speed=metricPair(d.metrics,'pagespeed')[0] as SpeedResult|undefined;
 const idx=metricPair(d.metrics,'indexation')[0];
 const schemas=(d.discoveries.schemas||[]) as {url:string;types:unknown[];valid?:boolean}[];const present=schemas.filter(s=>s.types.length);const valid=present.filter(s=>s.valid).length;
 return <>
 <section className="card store-score-hero" aria-label="Store Score"><div className="card-head"><h2>Store Score</h2><label>Trend period<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value="7">7 days</option><option value="28">28 days</option><option value="90">90 days</option></select></label></div><strong className="store-score-number">{n(score.score)}</strong><p>{delta===null?'History starts with recorded measurements; a comparison will appear when the selected period is available.':`${delta>=0?'+':''}${delta} points${baseline.score>0?` (${delta>=0?'+':''}${(100*delta/baseline.score).toFixed(1)}%)`:''} over ${days} days.`}</p>{score.limited&&<p className="badge">Limited evidence{score.capped?' · capped at 55':''} · {score.coverage}% of weighted components measured</p>}
 {trend.length>1&&<svg viewBox="0 0 600 100" role="img" aria-label="Recorded Store Score trend" className="score-sparkline"><polyline fill="none" stroke="currentColor" strokeWidth="3" points={trend.map((m,i)=>`${5+590*i/(trend.length-1)},${95-.9*m.score}`).join(' ')}/></svg>}
 <details><summary>What changed and how the score works</summary><p>A RankPilot indicator, not a Google rating. Missing components are excluded and remaining weights are rescaled; this makes it a partial score. Fewer than 10 clicks or missing recent search evidence caps the headline at 55. Grey components have limited evidence. Readiness and content coverage overlap other components by design.</p><div className="table-wrap"><table><thead><tr><th>Component</th><th>Weight</th><th>Now</th><th>Movement</th><th>Evidence</th></tr></thead><tbody>{score.parts.map(p=>{const before=baseline?.parts?.find((b:{key:string})=>b.key===p.key)?.value;return <tr key={p.key} className={p.low?'limited-evidence':''}><td>{p.label}</td><td>{p.weight}%</td><td>{n(p.value)}</td><td>{before!=null&&p.value!==null?`${(p.value-before).toFixed(1)} points`:'No comparable baseline'}</td><td>{p.low?'Low confidence. ':''}{p.note}</td></tr>;})}</tbody></table></div><p>Fixes saved in the same period are listed below. Their timing does not prove they caused a score, traffic or revenue movement. A score can change when new evidence arrives, even with no content edits.</p>{d.changes.filter(c=>c.appliedAt&&now-new Date(c.appliedAt).getTime()<=days*86400000).slice(0,10).map(c=><p key={c.id}>{new Date(c.appliedAt!).toLocaleDateString('en-GB')} · {d.resources.find(r=>r.id===c.resourceId)?.title||'Store update'} · {c.feature} · {c.status==='rolled_back'?'Undone':'Applied'}</p>)}<Link to="/app/reports">Open complete change history and impact tracking →</Link></details></section>
 <div className="metrics-grid search-score-grid">
 <Tile label="Google search visibility" value={n(score.search?.score)} low={score.parts[0].low}><p>{score.search?`${score.search.clicks} clicks / ${score.search.impressions} impressions · ${score.search.start} to ${score.search.end}.`:'Connect Search Console and refresh analytics.'}</p><p>{visibilityMethod}</p><Link to="/app/reports">Explore the searches that reach your shop →</Link></Tile>
 <Tile label="Technical health" value={n(latest?.score)}><p>Catalogue checks that pass. This measures page setup, not search position. Fix the highest-priority issues below; live link, speed and schema checks are reported separately.</p><Link to="/app/audit">Inspect checks and scan coverage →</Link></Tile></div>
 <div className="metrics-grid dashboard-metrics">
 <Tile label="Discovery readiness" value={n(score.readiness)} low={score.parts[2].low}><p>{score.parts[2].note} Missing search data leaves this unmeasured.</p><Link to="/app/audit">Find the next improvement →</Link></Tile>
 <Tile label="AI visibility" value={score.ai===null?'Not measured':`${Math.round(score.ai)}%`} low={score.samples<10}><p>{score.parts[3].note} API observations do not represent all consumer answers.</p><Link to="/app/aeo">Explore AI visibility and FAQs →</Link></Tile>
 <Tile label="Organic revenue" value={money(ga)}><p>{ga?.start?`${ga.start} to ${ga.end} · Google Analytics Organic Search attribution.`:'Connect Google Analytics and refresh analytics.'} This is attributed revenue, not proof a RankPilot edit caused a sale.</p><Link to="/app/reports">See revenue evidence →</Link></Tile>
 <Tile label="AI referral revenue" value={money(ai)}><p>{ai?.start?`${ai.start} to ${ai.end}.`:''} Google Analytics sessions with identifiable AI referrers. Unidentified referrers are not measurable; this is not a Shopify order-level reconciliation.</p><Link to="/app/reports">See recorded referrals →</Link></Tile></div>
 <div className="catalogue-tiles">{[['product','Products','products'],['collection','Collections','collections'],['article','Blogs','content']].map(([kind,label,path])=>{const performance=searchVisibility(gsc,kind,now);return <div className="card catalogue-tile" key={kind}><Link to={`/app/${path}`}><h2>{label} ↗</h2><strong>{n(d.healthScores?.[kind]?.score)}</strong></Link><details><summary>How this is measured / what to do</summary><p>Technical health across {d.resources.filter(r=>r.kind===kind).length} pages. Open {label.toLowerCase()} to review source-based suggestions. Search visibility: {n(performance?.score)}; {performance?.clicks??'unmeasured'} reported clicks. Setup and traffic are different measures.</p></details></div>;})}</div>
 <div className="metrics-grid additional-metrics">
 <Tile label="Store speed / Core Web Vitals" value={n(speed?.score==null?null:speed.score*100)}><p>{speed?.url||'Run a mobile speed check.'} {speed?.checkedAt?`Checked ${new Date(speed.checkedAt).toLocaleString('en-GB')}.`:''} Score is a Lighthouse lab measurement, not a Core Web Vitals pass.</p>{['LARGEST_CONTENTFUL_PAINT_MS','CUMULATIVE_LAYOUT_SHIFT_SCORE','INTERACTION_TO_NEXT_PAINT'].map(k=><p key={k}>{fieldMeasurement(k,speed?.field?.metrics?.[k]?.percentile)}</p>)}<Link to="/app/reports#page-speed">Run a check and review speed improvements →</Link></Tile>
 <Tile label="Indexation coverage" value={idx?`${idx.indexed} / ${idx.submitted}`:'Not measured'}><p>{idx?`${idx.indexed} confirmed indexed of ${idx.submitted} URLs found in the sitemap; ${idx.inspected} inspected in the last 28 days. ${idx.submitted-idx.inspected} remain unknown.${idx.limited?' Sitemap discovery was limited; this is not the whole site.':''}`:'Check sitemap URLs against Google’s stored index, 20 per run. Unknown URLs are never counted as unindexed.'}</p><check.Form method="post" action="/app" preventScrollReset><input type="hidden" name="intent" value="indexation"/><button className="button" disabled={check.state!=='idle'}>{check.state==='idle'?'Check next 20 URLs':'Queuing…'}</button></check.Form>{check.data&&<p role="status">{check.data.message}</p>}{idx&&<details><summary>URL evidence and checks that need attention</summary><p>{idx.note}</p>{idx.errors?.map((e:string)=><p key={e}>{e}</p>)}{idx.rows?.map((r:{url:string;verdict?:string;coverageState?:string;error?:string;checkedAt:string})=><p key={r.url}>{r.url} · {r.error||r.coverageState||r.verdict} · {r.checkedAt}</p>)}</details>}</Tile>
 <Tile label="Structured-data health" value={present.length?`${valid} / ${present.length}`:'Not measured'}><p>{valid} pages pass RankPilot’s schema checks out of {present.length} scanned pages with schema. {schemas.length-present.length} scanned pages have none. This is a local validation result, not guaranteed Google rich-result eligibility.</p><Link to="/app/aeo">Inspect schema coverage and missing details →</Link></Tile>
 </div>
 </>;
}
export function StoreProgress({d}:{d:Data}){
 const rows=d.metrics.filter(m=>m.provider==='store-score').sort((a,b)=>a.period.localeCompare(b.period)).map(m=>({...JSON.parse(m.payload),day:m.period}));
 return <section className="card"><h2>Progress after your changes</h2><p>{d.appliedCount} verified changes saved. Store Score history starts with this release; no older points are invented.</p>{rows.length>1?<><svg viewBox="0 0 800 140" role="img" aria-label="Recorded Store Score and saved change counts" style={{width:'100%',height:170}}><line x1="15" x2="785" y1="125" y2="125" stroke="#dce3df"/><polyline fill="none" stroke="#27644e" strokeWidth="3" points={rows.filter(r=>r.score!==null).map((r,i)=>`${15+i*770/Math.max(1,rows.length-1)},${125-r.score}`).join(' ')}/></svg><details><summary>Recorded scores and fixes</summary><table><thead><tr><th>Date</th><th>Store Score</th><th>Saved changes</th></tr></thead><tbody>{rows.map(r=><tr key={r.day}><td>{r.day}</td><td>{r.score===null?'Not measured':`${r.score}/100`}</td><td>{r.appliedCount}</td></tr>)}</tbody></table></details></>:<p>Run a scan or refresh analytics to record a measurement. More dates will build the trend.</p>}<p>Score movement and fixes are shown together for context; this does not prove that a fix caused the movement. Open a saved fix in Results &amp; history for its own before/after search baseline.</p><Link to="/app/reports">Track saved fixes and results →</Link></section>;
}
