import {searchVisibility,discoveryReadiness,visibilityMethod} from '../core/visibility-score';
import {findingImpact,findingName} from '../core/merchant-copy';
import {TrafficTrend} from './TrafficTrend';
import {useState} from 'react';
import {Link,useSearchParams} from 'react-router';
import type {loadUI} from '../core/ui.server';
import type {Issue} from '../core/types';
import {actionGroups,opportunityQueries} from '../core/dashboard';
import {metricPair} from '../core/analytics';
import {BatchReview} from './BatchReview';
import {reviewable} from '../core/workflow-ui';
type Data=Awaited<ReturnType<typeof loadUI>>;
export function Dashboard({d,issues,busy,onFix,onReview,onReviewReady}:{d:Data;issues:Issue[];busy:boolean;onFix:(issues:Issue[])=>void;onReview:(id:string)=>void;onReviewReady:()=>void}){
 const [params]=useSearchParams();const [all,setAll]=useState(false);const [queue,setQueue]=useState(params.get('review')==='ready');
 const ready=d.changes.filter(c=>c.status==='pending'&&reviewable(c));
 const groups=actionGroups(issues);const latest=d.audits[0];
 const ga=metricPair(d.metrics,'ga4')[0];const ai=metricPair(d.metrics,'ga4-ai')[0];const gsc=metricPair(d.metrics,'gsc')[0];
 const money=(m:typeof ga)=>m?.rows ? new Intl.NumberFormat('en-GB',{style:'currency',currency:m.currency||'GBP'}).format(m.rows.reduce((n:number,r:{metricValues?:{value:string}[]})=>n+Number(r.metricValues?.[1]?.value||0),0)):'Not measured';
 const measuredAt=Date.parse(d.measuredAt);
 const samples=d.observations.filter(o=>measuredAt-new Date(o.createdAt).getTime()<=28*86400000);const cited=samples.filter(o=>o.cited).length;
 const competitors=new Map<string,number>();for(const o of samples.filter(o=>!o.cited)){try{for(const c of JSON.parse(o.competitors))if(typeof c==='string')competitors.set(c,(competitors.get(c)||0)+1);}catch{/* no structured evidence */}}
 const competitor=[...competitors].sort((a,b)=>b[1]-a[1])[0];
 const opportunities=opportunityQueries(gsc?.rows);
 const trend=[...d.audits].reverse();
 const coverage=latest?JSON.parse(latest.coverage):{};
 const visibility=searchVisibility(gsc,undefined,measuredAt);const readiness=discoveryReadiness(latest?.score,visibility,{cited,total:samples.length});
 return <>
 <div className="metrics-grid dashboard-metrics">
 <div className="metric"><div>Discovery readiness</div><strong>{readiness===null?'Not measured':`${readiness}/100`}</strong><small>Combines technical setup with observed search and recent AI visibility.</small></div>
 <Link className="metric metric-link" to="/app/aeo"><div>AI visibility ↗</div><strong>{samples.length?`${Math.round(100*cited/samples.length)}%`:'Not measured'}</strong><small>{cited} cited answers / {samples.length} recorded samples. Open FAQs and AI visibility.</small></Link>
 <div className="metric"><div>Organic revenue</div><strong>{money(ga)}</strong><small>{ga?.start?`${ga.start} to ${ga.end} · Google Analytics attribution`:'Connect Google Analytics in Settings'}</small></div>
 <div className="metric"><div>AI referral revenue</div><strong>{money(ai)}</strong><small>{ai?.start?`${ai.start} to ${ai.end} · identifiable AI referrals in Analytics`:'Refresh connected analytics to measure identifiable AI referrals'}</small></div>
 </div>
 <section className="card" aria-label="Search performance"><div className="metrics-grid search-score-grid">
 <div className="metric"><div>Google search visibility</div><strong>{visibility?.score!=null?`${visibility.score}/100`:'Not measured'}</strong><small>How often reported searches show you near the top and earn a click.</small></div>
 <div className="metric"><div>Technical health</div><strong>{latest?`${latest.score}/100`:'Not checked'}</strong><small>How many catalogue checks pass. This measures page setup; search performance is shown alongside.</small></div>
 </div><p>{visibility?`${visibility.clicks} reported clicks · ${visibility.impressions} impressions · ${visibility.pages} pages with observed searches · ${visibility.start||'?'} to ${visibility.end||'?'}.`:'Connect Search Console and refresh analytics to measure search visibility.'} {visibility?.position!=null?`Average position ${visibility.position.toFixed(1)}.`:''} {visibility?.lowSample?'Limited evidence: small samples can move sharply.':''} {visibility?.stale?'This snapshot is stale; refresh connected analytics.':''}</p><details><summary>How these scores work</summary><p>{visibilityMethod}</p><p>These are RankPilot indicators, not Google ratings or a promise of page-one rankings. Branded searches may dominate the reported data.</p></details></section>
 <div className="dashboard-grid">
 <section className="card"><div className="card-head"><h2>Fix these next</h2><button className="button" onClick={onReviewReady}>Review ready fixes ({ready.length})</button></div><p className="muted">Clear failures first, then useful improvements. Nothing is published until you approve.</p>{coverage.lastLinkRecheck&&<p role="status">Latest link check: {coverage.lastLinkRecheck.address} · {coverage.lastLinkRecheck.resolved?`${coverage.lastLinkRecheck.removed} findings cleared after a successful live check.`:`Still needs attention${coverage.lastLinkRecheck.status?` (HTTP ${coverage.lastLinkRecheck.status})`:""}; findings retained.`} Checked {new Date(coverage.lastLinkRecheck.checkedAt).toLocaleString("en-GB")}.</p>}
 {(all?groups:groups.slice(0,5)).map(g=>{const ids=[...new Set(g.items.map(i=>i.resourceId))];const proposals=ready.filter(c=>ids.includes(c.resourceId)&&g.items.some(i=>i.feature===c.feature));return <div className="priority" key={g.key}><span className={'badge '+(g.priority===0?'red':g.priority<3?'amber':'neutral')}>{g.priority===0?'High':g.priority<3?'Medium':'Optional'}</span><div><h3>{g.code==='google-listings'?'Improve Google titles and summaries':findingName(g.code)}</h3>{g.destination&&<p>Shared destination: {g.destination}</p>}<p className="muted">{findingImpact(g.items[0]).impact} · {findingImpact(g.items[0]).effort}</p><small>{g.count} affected {g.count===1?'page':'pages'} · {g.occurrences} checks</small><details><summary>Why and how to fix</summary><p>{g.items[0].detail}</p><Link to={`/app/audit?finding=${encodeURIComponent(g.items[0].code)}`}>See affected pages and evidence</Link></details></div><button className="button" disabled={busy} onClick={()=>onFix([...g.items].sort((a,b)=>Number(proposals.some(c=>c.resourceId===b.resourceId&&c.feature===b.feature))-Number(proposals.some(c=>c.resourceId===a.resourceId&&c.feature===a.feature))))}>{proposals.length?`Review a fix (${proposals.length})`:'Inspect & fix'}</button></div>})}
 {!groups.length&&<p>{latest?'No findings in the completed checks. Review scan coverage before assuming every page is healthy.':'Run your first scan to prioritise fixes.'}</p>}
 {groups.length>5&&<button className="text-link" onClick={()=>setAll(!all)}>{all?'Show top five':`See all ${groups.length} issue groups`}</button>}
 <p><Link to="/app/audit#technical-tools">Manage broken URLs and technical checks</Link> · <Link to="/app/reports#page-speed">Check page speed</Link></p>
 {opportunities.length>0&&<p><Link to="/app/reports">Explore {opportunities.length} searches at positions 8–20</Link></p>}
 </section>
 <section className="card"><h2>AI answer engines</h2>{[['openai','ChatGPT API'],['perplexity','Perplexity'],['gemini','Gemini'],['Google AI Overviews','Google AI Overviews']].map(([key,label])=>{const rows=samples.filter(o=>o.engine===key);return <div className="mini-stat" key={key}><span>{label}</span><strong>{rows.length?`Cited ${rows.filter(o=>o.cited).length}/${rows.length}`:'Not measured'}</strong></div>})}<p>API samples are dated observations, not consumer search rankings. Google AI Overviews requires a separate observation source.</p><p>{competitor?`Most frequently recorded alternative: ${competitor[0]} (${competitor[1]} samples).`:'No competing citations recorded yet.'}</p><Link className="button" to="/app/aeo">Explore AI visibility &amp; FAQs</Link><p className="muted">Crawler access and confirmed product details are checked separately.</p></section>
 </div>
 {ready.length>0 && <p><button className="text-link" onClick={()=>{setQueue(true);requestAnimationFrame(()=>document.getElementById('dashboard-review')?.scrollIntoView({block:'start'}));}}>Review as a set</button></p>}
 {queue&&<section id="dashboard-review"><h2>Review and approve here</h2><BatchReview changes={ready} resources={d.resources}/>{ready.map(c=><div className="mini-stat" key={c.id}><span>{d.resources.find(r=>r.id===c.resourceId)?.title||'Page'}</span><button className="button" onClick={()=>onReview(c.id)}>Review</button></div>)}{!ready.length&&<p>No ready previews. Generate a fix above to start.</p>}<details><summary>Older drafts and work in progress</summary>{d.changes.filter(c=>!reviewable(c)&&!['applied','rejected','rolled_back','superseded'].includes(c.status)).map(c=><p key={c.id}>{d.resources.find(r=>r.id===c.resourceId)?.title}<button className="button" onClick={()=>onReview(c.id)}>Open details</button></p>)}</details></section>}
 <TrafficTrend daily={metricPair(d.metrics,'gsc-daily')[0]} observations={d.observations}/>
 <details className="card"><summary>Store-health score history</summary><h2>Progress over time</h2><p>Recorded store-health checks. Scores cover catalogue checks only; they do not prove changes caused more sales.</p>{trend.length>1?<><svg viewBox="0 0 800 140" role="img" aria-label="Catalogue health scores across recorded audits" style={{width:'100%',height:160}}><line x1="15" x2="785" y1="125" y2="125" stroke="#dce3df"/><polyline fill="none" stroke="#27644e" strokeWidth="3" points={trend.map((a,i)=>`${15+i*770/(trend.length-1)},${125-a.score}`).join(' ')}/></svg><div className="mini-stat"><span>{new Date(trend[0].createdAt).toLocaleDateString('en-GB')}</span><span>{new Date(trend.at(-1)!.createdAt).toLocaleDateString('en-GB')}</span></div><details><summary>View recorded scores</summary>{trend.map(a=><p key={a.id}>{new Date(a.createdAt).toLocaleString('en-GB')}: {a.score}/100</p>)}</details></>:<p>Run another audit to build a real trend. No sample trend is shown.</p>}<Link to="/app/reports">Explore traffic, revenue and change history</Link></details>
 <div className="catalogue-tiles">{[['product','Products','products'],['collection','Collections','collections'],['article','Blogs','content']].map(([kind,label,path])=>{const records=d.resources.filter(r=>r.kind===kind);const health=d.healthScores?.[kind];const performance=searchVisibility(gsc,kind,measuredAt);return <Link className="card catalogue-tile" to={`/app/${path}`} key={kind}><h2>{label} ↗</h2><strong>{!health?'Not checked':`${health.score}/100`}</strong><p>Technical health · {records.length} pages · catalogue health{health?` · ${health.checks-health.failed} of ${health.checks} checks passed`:""}. A warning lowers the score without marking the whole page unhealthy. Live link and speed findings appear in Fix these next.</p><p><b>Search visibility: {performance?.score!=null?`${performance.score}/100`:'Not measured'}</b> · {performance?.clicks??'—'} reported clicks · {performance?.impressions??'—'} impressions{performance?.position!=null?` · average position ${performance.position.toFixed(1)}`:''}. {performance?.lowSample?'Small sample; compare cautiously.':''}</p></Link>})}</div>
 <details className="card"><summary>How to use this dashboard and what has been checked</summary><p>Start with one of the five priority groups. Generate a preview, check the proposed change, then approve it here. Use the product, collection and blog tiles for individual pages; open AI visibility for FAQs and recorded answers. Saved changes and undo options are in Results &amp; history.</p><p>{latest?`${coverage.catalogue||0} catalogue records and ${coverage.storefront||0} live pages checked. ${coverage.linkChecks?.checked||0} link destinations tested.`:'No completed audit yet.'}</p><p>{coverage.linkChecks?.skipped?`${coverage.linkChecks.skipped} link destinations were outside this scan’s limits. `:''}{coverage.linkChecks?.unavailable?`${coverage.linkChecks.unavailable} destinations could not be confirmed. `:''}Historical missing addresses are checked when you import them. Technical health counts catalogue checks. Search visibility uses the dated Search Console observations shown above; missing data stays unmeasured.</p><Link to="/app/audit">Open all checks, missing URLs and technical fixes</Link></details>
 </>;
}
