// Local demo-only regression test. Never opens Shopify or uses production credentials.
import {spawn} from 'node:child_process';
import {createCipheriv,randomBytes} from 'node:crypto';
import {setTimeout as wait} from 'node:timers/promises';
import {chromium,expect} from '@playwright/test';
import portable from '@sparticuz/chromium';
import {mkdirSync,writeFileSync,readFileSync,chmodSync,existsSync} from 'node:fs';
import {brotliDecompressSync} from 'node:zlib';
import {spawnSync} from 'node:child_process';
import {createCookie} from 'react-router';
import {PrismaClient} from '@prisma/client';
const env={...process.env,DEMO_MODE:'true',DATABASE_URL:'file:/tmp/rankpilot-feedback6.sqlite',SHOPIFY_APP_URL:'http://localhost:3016',ENCRYPTION_KEY:'a'.repeat(64),SHOPIFY_API_KEY:'local-test-key',PORT:'3016',HOST:'127.0.0.1'};
const db=new PrismaClient({datasources:{db:{url:env.DATABASE_URL}}});
const server=spawn('node',['./node_modules/@react-router/serve/bin.js','./build/server/index.js'],{env,stdio:['ignore','pipe','pipe']});
let logs='';server.stdout.on('data',d=>logs+=d);server.stderr.on('data',d=>logs+=d);
let browser;
try {
 for(let i=0;i<60;i++){try{if((await fetch('http://localhost:3016/health')).ok)break;}catch{}await wait(250);if(i===59)throw new Error(logs);}
 const runtime=process.cwd()+'/.browser-runtime';mkdirSync(runtime,{recursive:true});
 const executablePath=runtime+'/chromium';
 if(!existsSync(executablePath)){writeFileSync(executablePath,brotliDecompressSync(readFileSync('node_modules/@sparticuz/chromium/bin/chromium.br')));chmodSync(executablePath,0o755);}
 for(const name of ['fonts','swiftshader']){const target=name==='fonts'?runtime+'/fonts':runtime;mkdirSync(target,{recursive:true});const tar=runtime+'/'+name+'.tar';writeFileSync(tar,brotliDecompressSync(readFileSync('node_modules/@sparticuz/chromium/bin/'+name+'.tar.br')));spawnSync('tar',['--no-same-owner','-xf',tar,'-C',target]);}
 writeFileSync(runtime+'/fonts/fonts.conf',`<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "fonts.dtd"><fontconfig><dir>${runtime}/fonts/fonts</dir><dir>/usr/share/fonts</dir><cachedir>${runtime}/font-cache</cachedir></fontconfig>`);
 process.env.FONTCONFIG_PATH=runtime+'/fonts';process.env.LD_LIBRARY_PATH=runtime;
 browser=await chromium.launch({executablePath,args:portable.args.filter(a=>!a.includes('disable-web-security')),headless:true});
 const page=await browser.newPage();page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:3016/app/audit');
 const type=page.getByLabel('Filter finding type');await type.selectOption('missing-alt');
 await expect(type).toHaveValue('missing-alt');
 await page.reload();await expect(type).toHaveValue('missing-alt');
 const rows=page.locator('table').filter({has:page.getByRole('columnheader',{name:'Page & finding',exact:true})}).locator('tbody tr');
 expect(await rows.count()).toBeGreaterThan(0);
 for(const row of await rows.all())await expect(row).toContainText('One or more images have no description');
 console.log('PASS finding filter applies and survives reload');
 // Change a queued job to completed from outside the page. No navigation/reload.
 const cookie=(await page.context().cookies()).find(c=>c.name==='rankpilot_demo');
 const storeId=await createCookie('rankpilot_demo',{secrets:[env.SESSION_SECRET || 'local-demo-only']}).parse('rankpilot_demo='+cookie.value);
 const store=await db.store.findUniqueOrThrow({where:{id:storeId}});

 const cfg=JSON.parse(store.settings);cfg.reportedPaths=['/products/retired-fixture'];
 await db.store.update({where:{id:store.id},data:{settings:JSON.stringify(cfg),discoveries:JSON.stringify({reported:[{path:'/products/retired-fixture',status:404,state:'Missing page'}]})}});
 await page.reload();
 await page.getByRole('button',{name:'Redirect to another page',exact:true}).click();
 await expect(page.getByRole('textbox',{name:'Old path',exact:true})).toHaveValue('/products/retired-fixture');
 await page.getByRole('button',{name:'Remove from tracking',exact:true}).click();
 await expect(page.getByText('Removed from tracking. No Shopify page or redirect was deleted.',{exact:false})).toBeVisible();
 await expect(page.getByRole('button',{name:'Remove from tracking',exact:true})).toHaveCount(0);
 expect(JSON.parse((await db.store.findUniqueOrThrow({where:{id:store.id}})).settings).reportedPaths).toEqual([]);
 console.log('PASS old URL redirect selection and removal from tracking');
 const job=await db.job.create({data:{storeId:store.id,kind:'audit',status:'running',dedup:crypto.randomUUID(),payload:'{}'}});
 await expect(page.getByText('Latest audit job: running')).toBeVisible({timeout:20000});
 await db.job.update({where:{id:job.id},data:{status:'completed',payload:JSON.stringify({result:{score:80}})}});
 await expect(page.getByText('Latest audit job: completed')).toBeVisible({timeout:15000});
 console.log('PASS external job completion appears without refresh');
 const product=await db.resource.findFirstOrThrow({where:{storeId:store.id,kind:'product'}});
 await db.resource.update({where:{id:product.id},data:{facts:'{}'}});
 await page.goto('http://localhost:3016/app/products');
 await page.getByLabel('CSV contents').fill(`handle,materials,source\n${product.handle},Steel,Local supplier fixture`);
 await page.getByRole('button',{name:'Preview import',exact:true}).click();
 await expect(page.getByText(/Matched 1 products/)).toBeVisible();
 await page.getByRole('button',{name:'Import unconfirmed facts',exact:true}).click();
 await expect(page.getByText(/Imported .*unconfirmed facts/)).toBeVisible();
 const saved=await db.resource.findUniqueOrThrow({where:{id:product.id}});
 const fact=JSON.parse(saved.facts).materials;
 if(fact.confirmed)throw new Error('Imported fact was incorrectly confirmed');
 console.log('PASS CSV preview and import retains unconfirmed source-backed fact');
 await db.change.createMany({data:[{storeId:store.id,resourceId:product.id,feature:'seo',before:'{}',after:JSON.stringify({title:'Camping mug',description:'A camping mug.'}),reasons:JSON.stringify(['source-reviewed-v1: Current review']),blockers:'[]'},{storeId:store.id,resourceId:product.id,feature:'seo',before:'{}',after:JSON.stringify({title:'Old mug',description:'An older mug.'}),reasons:JSON.stringify(['source-reviewed-v1: The existing Shopify page title is reused']),blockers:'[]'}]});
 await page.goto('http://localhost:3016/app/reviews');
 await expect(page.getByRole('button',{name:'Ready to accept (1)',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Needs attention (1)',exact:true})).toBeVisible();
 console.log('PASS ready and blocked review counts are separate');
 await page.goto('http://localhost:3016/app');
 await expect(page.getByRole('navigation',{name:'Main navigation'}).getByRole('link')).toHaveCount(3);
 await page.getByRole('button',{name:'Review ready fixes (1)',exact:true}).click();
 await expect(page.locator('dialog.change-preview')).toBeVisible();
 await expect(page.locator('dialog.change-preview').getByRole('button',{name:'Before',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Close preview',exact:true}).click();
 await page.getByRole('button',{name:'Review as a set',exact:true}).click();
 console.log('PASS Review ready fixes opens the first preview immediately');
 await page.getByText('How your page looks on Google — 1 ready',{exact:true}).click();
 const batchButton=page.getByRole('button',{name:'Accept and apply this set (1)',exact:true});
 await expect(batchButton).toBeDisabled();
 await page.getByLabel('I approve these 1 previews.').check();
 await batchButton.click();
 await expect(page.getByText(/1 changes accepted and queued to save/)).toBeVisible();
 expect(await db.change.count({where:{storeId:store.id,status:'approved'}})).toBe(1);
 expect(await db.change.count({where:{storeId:store.id,status:'pending'}})).toBe(1);
 console.log('PASS explicit batch approval excludes blocked drafts');

 await page.goto('http://localhost:3016/app');
 await expect(page.getByRole('heading',{name:'Fix these next',exact:true})).toBeVisible();
 await expect(page.locator('.dashboard-metrics .metric')).toHaveCount(4);
 await expect(page.locator('.catalogue-tiles a')).toHaveCount(3);
 await page.screenshot({path:'/tmp/rankpilot-dashboard8.png',fullPage:true});
 console.log('PASS dashboard metrics, priority actions and content navigation');
 await page.goto('http://localhost:3016/app/settings');
 await expect(page.getByLabel('Brand suffix')).toBeVisible();
 const voice=page.locator('textarea[name="brandVoice"]');
 await voice.fill('Warm, clear British English. Keep our original stories.');
 await expect(voice).toHaveValue('Warm, clear British English. Keep our original stories.');
 await wait(5500);
 await expect(voice).toHaveValue('Warm, clear British English. Keep our original stories.');
 console.log('BRAND FIELD',await voice.evaluate(e=>({disabled:e.disabled,readOnly:e.readOnly,background:getComputedStyle(e).backgroundColor})));
 console.log('PASS brand voice accepts typing and survives background polling');
 await page.getByLabel('Brand suffix').selectOption('omit');
 await page.getByRole('button',{name:'Save settings',exact:true}).click();
 await expect(page.getByText('Settings saved.',{exact:false})).toBeVisible().catch(async()=>{const cfg=JSON.parse((await db.store.findUniqueOrThrow({where:{id:store.id}})).settings);expect(cfg.titleBrandMode).toBe('omit');});
 // Simulate the embedded branch in an iframe. Shopify is not contacted: a
 // local ID-token stub and request guard exercise the production client path.
 const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',Buffer.from(env.ENCRYPTION_KEY,'hex'),iv);
 const encrypted=Buffer.concat([cipher.update(JSON.stringify({openaiKey:'local-unused-fixture'}),'utf8'),cipher.final()]);
 const fixtureCredential=['v1',iv.toString('base64'),cipher.getAuthTag().toString('base64'),encrypted.toString('base64')].join('.');
 await db.store.update({where:{id:store.id},data:{demo:false,credentials:fixtureCredential}});
 await page.context().addInitScript(()=>{window.shopify={idToken:async()=> 'local-embedded-test-token'};});
 await page.context().route('https://cdn.shopify.com/shopifycloud/app-bridge.js',r=>r.fulfill({contentType:'text/javascript',body:''}));
 let failedStatus=true,authenticatedPolls=0;
 await page.context().route('**/app/job-status',r=>{
   if(r.request().headers().authorization!=='Bearer local-embedded-test-token')return r.fulfill({status:401,body:'Missing authentication'});
   authenticatedPolls++;
   if(failedStatus)return r.fulfill({status:503,body:'Temporary outage'});
   return r.continue();
 });
 // The real app permits only Shopify frame ancestors. This fixture uses a
 // local parent, so remove that header from the local test response only.
 await page.context().route('http://localhost:3016/app/audit',async r=>{
   const response=await r.fetch();const headers={...response.headers()};
   delete headers['content-security-policy'];delete headers['x-frame-options'];
   await r.fulfill({response,headers});
 });
 await page.context().route('http://localhost:3016/test-frame',r=>r.fulfill({contentType:'text/html',body:'<iframe title="Local embedded app" src="http://localhost:3016/app/audit" style="width:1500px;height:1000px"></iframe>'}));
 await page.goto('http://localhost:3016/test-frame');
 const frame=page.frameLocator('iframe');
 await expect(frame.getByText(/Live progress is temporarily unavailable/)).toBeVisible({timeout:15000});
 const embedFilter=frame.getByLabel('Filter finding type');
 await embedFilter.selectOption('missing-alt');await expect(embedFilter).toHaveValue('missing-alt');
 failedStatus=false;
 await expect(frame.getByText(/Live progress is temporarily unavailable/)).toHaveCount(0,{timeout:15000});
 // Start a real generation request, then supply the worker result in this
 // isolated database. No AI or Shopify writes are involved.
 await frame.getByRole('button',{name:'Generate fix',exact:true}).first().click();
 let generated;
 for(let i=0;i<30;i++){generated=await db.job.findFirst({where:{storeId:store.id,kind:'optimise'},orderBy:{createdAt:'desc'}});if(generated)break;await wait(100);}
 if(!generated)throw new Error('Generation request not enqueued');
 const payload=JSON.parse(generated.payload);const rid=payload.ids[0];
 const change=await db.change.create({data:{storeId:store.id,resourceId:rid,feature:'alt',before:JSON.stringify([{id:'fixture-image',alt:''}]),after:JSON.stringify([{id:'fixture-image',alt:'A camping mug on a table.'}]),reasons:JSON.stringify(['image-reviewed-v1: local fixture']),blockers:'[]'}});
 await db.job.update({where:{id:generated.id},data:{status:'completed',payload:JSON.stringify({...payload,result:[{resourceId:rid,changeId:change.id}]})}});
 await expect(frame.locator('dialog.change-preview')).toBeVisible({timeout:15000});
 await expect(frame.getByRole('button',{name:'Accept and apply',exact:true})).toBeEnabled();
 await frame.getByRole('button',{name:'Close preview',exact:true}).click();
 await expect(embedFilter).toHaveValue('missing-alt');
 if(authenticatedPolls<2)throw new Error('Embedded polling did not authenticate');
 await db.store.update({where:{id:store.id},data:{demo:true}});
 console.log('PASS iframe filter, authenticated polling, outage recovery and generation completion without refresh');
 if(errors.length)throw new Error(errors.join('\n'));
 console.log('PASS metric and title preferences; no browser exceptions');
 // Reproduce reported usability paths against the real local React UI.
 await page.context().unroute('**/app/job-status');
 await page.goto('http://localhost:3016/app/settings');
 const savedVoice=page.getByLabel('Describe your brand’s tone');
 await expect(savedVoice).toHaveValue('Warm, clear British English. Keep our original stories.');
 expect(JSON.parse((await db.store.findUniqueOrThrow({where:{id:store.id}})).settings).brandVoice).toBe('Warm, clear British English. Keep our original stories.');
 console.log('PASS brand voice saved and reloads');
 await db.resource.createMany({data:Array.from({length:320},(_,i)=>({storeId:store.id,remoteId:'perf-'+i,kind:'product',title:'Performance fixture '+i,handle:'performance-'+i,payload:JSON.stringify({...JSON.parse(product.payload),images:[]})}))});
 await page.setViewportSize({width:1100,height:700});
 await page.goto('http://localhost:3016/app/products');
 const productRow=page.locator('tbody tr').filter({has:page.getByRole('checkbox',{name:'Select '+product.title,exact:true})});
 const selection=productRow.getByRole('checkbox');
 const selectedAt=Date.now();await selection.check();await expect(selection).toBeChecked({timeout:250});
 const selectionMs=Date.now()-selectedAt;expect(selectionMs).toBeLessThan(1000);console.log(`PASS selection confirmed in ${selectionMs}ms with 320 extra catalogue items`);
 await expect(page.getByText('1 selected',{exact:true})).toBeVisible({timeout:250});
 await productRow.getByRole('button',{name:'Product details',exact:true}).click();
 const factsModal=page.locator('dialog.facts-dialog');
 const saveFacts=factsModal.getByRole('button',{name:'Save product details',exact:true});
 await expect(saveFacts).toBeInViewport();
 const body=factsModal.locator('.facts-body');await body.hover();await page.mouse.wheel(0,1200);
 await expect.poll(()=>body.evaluate(e=>e.scrollTop)).toBeGreaterThan(0);
 await expect(saveFacts).toBeInViewport();
 await page.setViewportSize({width:390,height:700});await expect(saveFacts).toBeInViewport();
 await factsModal.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.setViewportSize({width:1100,height:700});
 console.log('PASS immediate selection feedback and modal wheel scrolling with visible Save/Cancel on desktop and mobile');
 // Delay receipt to prove progress is beside the clicked CTA, then complete the job externally.
 await page.route('**/app/products.data',async r=>{if(r.request().method()==='POST')await wait(800);await r.continue();});
 await page.getByRole('button',{name:'Generate previews',exact:true}).click();
 await expect(page.getByRole('button',{name:'Sending request…',exact:true})).toBeVisible();
 await expect(page.locator('.generation-feedback')).toContainText('Sending your request');
 await expect(page.getByRole('button',{name:'Preparing previews…',exact:true})).toBeVisible();
 const catalogueJob=await db.job.findFirstOrThrow({where:{storeId:store.id,kind:'optimise',status:'queued'},orderBy:{createdAt:'desc'}});
 const cataloguePayload=JSON.parse(catalogueJob.payload);
 const preview=await db.change.create({data:{storeId:store.id,resourceId:product.id,feature:'seo',before:JSON.stringify({title:'Original camping product',description:'Original summary.'}),after:JSON.stringify({title:'Camping product',description:'A useful sourced summary.'}),reasons:JSON.stringify(['source-reviewed-v1: Adds a specific description from the existing product information.']),blockers:'[]'}});
 await db.job.update({where:{id:catalogueJob.id},data:{status:'completed',payload:JSON.stringify({...cataloguePayload,result:[{resourceId:product.id,changeId:preview.id}]})}});
 const previewDialog=page.locator('dialog.change-preview');
 await expect(previewDialog).toBeVisible({timeout:15000});
 await expect(previewDialog.getByRole('heading',{name:'Why we suggest this',exact:true})).toBeVisible();
 await previewDialog.getByRole('button',{name:'Before',exact:true}).click();
 await expect(previewDialog.locator('.snippet')).toContainText('Original camping product');
 await previewDialog.getByRole('button',{name:'After',exact:true}).click();
 await expect(previewDialog.locator('.snippet')).toContainText('A useful sourced summary.');
 await previewDialog.getByRole('button',{name:'Close preview',exact:true}).click();
 console.log('PASS catalogue request receipt, running state and automatic reusable Before/After review');
 const latestAudit=await db.audit.findFirstOrThrow({where:{storeId:store.id},orderBy:{createdAt:'desc'}});
 const arenaIssues=[{resourceId:product.id,title:product.title,code:'missing-meta-description',severity:'critical',feature:'seo',detail:'The page needs a specific summary.'},{resourceId:'reported:/products/retired-test',title:'/products/retired-test',code:'reported-404',severity:'critical',detail:'Imported missing URL returns 404.'}];
 const arenaSettings=JSON.parse((await db.store.findUniqueOrThrow({where:{id:store.id}})).settings);arenaSettings.reportedPaths=['/products/retired-test'];
 await db.store.update({where:{id:store.id},data:{settings:JSON.stringify(arenaSettings)}});
 await db.audit.update({where:{id:latestAudit.id},data:{issues:JSON.stringify(arenaIssues)}});
 await page.goto('http://localhost:3016/app');
 await page.locator('.priority').filter({hasText:'Improve Google titles and summaries'}).getByRole('button').click();
 await expect(page).toHaveURL('http://localhost:3016/app');
 await expect(previewDialog.getByRole('heading',{name:'Why we suggest this',exact:true})).toBeVisible();
 await previewDialog.getByRole('button',{name:'Reject',exact:true}).click();
 await expect(previewDialog.getByText('Rejected. Your current content has been kept.')).toBeVisible();
 expect((await db.change.findUniqueOrThrow({where:{id:preview.id}})).status).toBe('rejected');
 await previewDialog.getByRole('button',{name:'Close preview',exact:true}).click();
 await page.locator('.priority').filter({hasText:'Repair a reported missing page'}).getByRole('button').click();
 await expect(page).toHaveURL('http://localhost:3016/app');
 await expect(previewDialog.getByRole('textbox',{name:'Old path',exact:true})).toHaveValue('/products/retired-test');
 await expect(previewDialog.getByRole('button',{name:'Prepare redirect preview',exact:true})).toBeVisible();
 await page.screenshot({path:'/tmp/rankpilot9-fix-arena.png'});
 const destination=await db.resource.findFirstOrThrow({where:{storeId:store.id,kind:'collection'}});
 await previewDialog.getByRole('textbox',{name:'Replacement path',exact:true}).fill('/collections/'+destination.handle);
 await previewDialog.getByRole('button',{name:'Prepare redirect preview',exact:true}).click();
 await expect(previewDialog.getByRole('heading',{name:'Why we suggest this',exact:true})).toBeVisible();
 await expect(previewDialog.locator('.review-values')).toContainText('/collections/'+destination.handle);
 await previewDialog.getByRole('button',{name:'Reject',exact:true}).click();
 await expect(previewDialog.getByText('Rejected. Your current content has been kept.')).toBeVisible();
 console.log('PASS redirect prepares into the same reusable approval panel and can be rejected');
 await previewDialog.getByRole('button',{name:'Close preview',exact:true}).click();
 console.log('PASS dashboard fixes open an in-place arena, show rationale, persist rejection and prepare redirects without navigation');
 const acceptResource=await db.resource.findFirstOrThrow({where:{storeId:store.id,kind:'product',id:{not:product.id}}});
 const acceptPreview=await db.change.create({data:{storeId:store.id,resourceId:acceptResource.id,feature:'seo',before:JSON.stringify(JSON.parse(acceptResource.payload).seo),after:preview.after,reasons:preview.reasons,blockers:'[]'}});
 await page.reload();
 await page.getByRole('button',{name:/^Review ready fixes \(/}).click();
 const readySelect=previewDialog.getByLabel('Ready fix');
 expect(await readySelect.locator('option').count()).toBeGreaterThan(1);
 await previewDialog.getByRole('button',{name:'Next fix →',exact:true}).click();
 await expect(readySelect).toHaveValue('1');
 await previewDialog.getByRole('button',{name:'← Previous fix',exact:true}).click();
 await previewDialog.getByRole('button',{name:'Approve demo change',exact:true}).click();
 await expect(previewDialog.getByText(/Done\. Your suggested Google listing/)).toBeVisible();
 expect((await db.change.findUniqueOrThrow({where:{id:acceptPreview.id}})).status).toBe('applied');
 expect(JSON.parse((await db.resource.findUniqueOrThrow({where:{id:acceptResource.id}})).payload).seo).toEqual(JSON.parse(preview.after));
 await previewDialog.getByRole('button',{name:'Close preview',exact:true}).click();
 console.log('PASS ready-fix queue opens directly, navigates forward/back and accepts the exact preview');
 await db.metric.create({data:{storeId:store.id,provider:'gsc',period:'2026-09-01:2026-09-28',payload:JSON.stringify({start:'2026-09-01',end:'2026-09-28',rows:[{keys:['https://example.test/a','two clicks'],clicks:2,impressions:19,position:10},{keys:['https://example.test/b','zero clicks'],clicks:0,impressions:9,position:12},{keys:['https://example.test/c','tiny rate'],clicks:1,impressions:10000,position:15}]})}});
 await page.goto('http://localhost:3016/app/reports');
 const queries=page.locator('table').filter({has:page.getByRole('columnheader',{name:'Click rate',exact:true})});
 await expect(queries.locator('tr').filter({hasText:'two clicks'})).toContainText('10.5%');
 await expect(queries.locator('tr').filter({hasText:'zero clicks'})).toContainText('0%');
 await expect(queries.locator('tr').filter({hasText:'tiny rate'})).toContainText('<0.1%');
 await expect(page.getByText('Google search clicks',{exact:true})).toBeVisible();
 await expect(page.getByText('Search-engine sessions',{exact:true})).toBeVisible();
 if(errors.length)throw new Error(errors.join('\n'));
 console.log('PASS real row-derived click rates, distinguishable sources and no browser errors');
 await db.store.update({where:{id:store.id},data:{credentials:'{}'}});
 await page.goto('http://localhost:3016/app/products');
 await page.getByRole('checkbox',{name:'Select '+product.title,exact:true}).check();
 await page.getByRole('button',{name:'Generate previews',exact:true}).click();
 await expect(page.locator('.generation-feedback')).toContainText('Connect an OpenAI API key');
 await expect(page.getByRole('button',{name:'Generate previews',exact:true})).toBeEnabled();
 console.log('PASS generation failures appear beside the action and allow a corrected retry');

} finally {await browser?.close();server.kill();await db.$disconnect();}
