import {useState} from 'react';
import {useFetcher,useFormAction} from 'react-router';
import type {FactImportItem} from '../core/fact-import';
export function FactImport(){
 const fetcher=useFetcher<{ok:boolean;message:string;factImport?:FactImportItem[];csv?:string}>();
 const action=useFormAction();const [csv,setCsv]=useState('');
 const preview=fetcher.data?.csv===csv?fetcher.data.factImport:undefined;
 const busy=fetcher.state!=='idle';
 return <section className="card"><h2>Import sourced product facts</h2><p>Preview up to 500 products from a supplier CSV. Verified facts are protected.</p><details><summary>Why this matters and how to use it</summary><p>Source-backed facts help generate accurate FAQs without inventing specifications. Rename supplier columns to the headings below. Use each Shopify product handle to match it, then add a source URL or document reference for each fact. Imported values remain unconfirmed: open Facts &amp; keyword, check the source, and confirm accurate values before FAQ generation.</p><p>Columns: handle, source, dimensions, weight, materials, power, compatibility, included, care. Optional per-field references use dimensions_source, weight_source, etc. Omit columns you do not need. Existing confirmed facts are never overwritten.</p><pre>handle,materials,source{'\n'}example-product,Stainless steel,Supplier specification sheet page 2</pre></details><label>Supplier CSV file<input type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];if(file && file.size<=500000)setCsv(await file.text());else if(file)setCsv('File too large. Choose a CSV under 500 KB.');}}/></label><label>CSV contents<textarea rows={5} value={csv} onChange={e=>setCsv(e.target.value)}/></label><button className="button" disabled={busy || !csv.trim()} onClick={()=>fetcher.submit({intent:'previewFactsImport',csv},{method:'post',action})}>Preview import</button>{fetcher.data && <p role="status">{fetcher.data.message}</p>}{preview && <><ul>{preview.map(r=><li key={r.id}>{r.title}: {r.count} unconfirmed facts to import</li>)}</ul><button className="button primary" disabled={busy || !preview.some(r=>r.count)} onClick={()=>fetcher.submit({intent:'importFacts',csv},{method:'post',action})}>Import unconfirmed facts</button></>}</section>;
}
